(function(_ds){var window=this;'use strict';var aU=function(){var a=_ds.ci.call(this)||this;a.C=new _ds.Il;a.D=new _ds.Il;a.m=new Set;a.h=null;"IntersectionObserver"in window&&(a.h=new IntersectionObserver(function(b){b=_ds.p(b);for(var c=b.next();!c.done;c=b.next())c=c.value,c.isIntersecting&&(c=c.target,_ds.EG(new _ds.CG,c),a.m.delete(c),a.h.unobserve(c))},{rootMargin:"100%"}));return a},bU=function(a){Array.from(a.getElementsByTagName("table")).forEach(function(b){if(!b.parentNode.classList.contains("devsite-table-wrapper")){var c=
document.createElement("div");c.classList.add("devsite-table-wrapper");b.classList.contains("full-width")&&(c.classList.add("devsite-full-width-table"),b.classList.remove("full-width"));_ds.Kk(c,b);c.appendChild(b)}})},jU=function(a,b){var c,d,e,f,h,k,l;return _ds.Va(function(m){if(1==m.j)return _ds.A(m,DevsiteApp.whenReady(),2);c=_ds.nm();d=DevsiteApp.getInsecureHost();e=b.oa;if(e.origin!==c.origin&&d&&e.origin!==d)return m.return();try{f=_ds.Gg(_ds.Ao,e.data)}catch(n){return m.return()}h=_ds.mg(f,
1,0);if(4===h)return cU(a,e),m.return();k=f.getName();if(!k)return m.return();if(l=a.querySelector('devsite-iframe iframe[name="'+k+'"]'))switch(h){case 5:dU(f,l);break;case 8:eU(e,f,c);break;case 1:fU(e,f,c);break;case 6:case 7:gU(h,c,f);break;case 9:hU(a,f);break;case 10:iU(f,c)}_ds.B(m)})},dU=function(a,b){var c,d,e,f;_ds.Va(function(h){c=_ds.Ak(document).y;d=_ds.Kg(a,4);e=_ds.Kg(a,3);f=_ds.Vk(b);d&&f.setAttribute("width",d+"px");e&&f.setAttribute("height",e+"px");window.requestAnimationFrame(function(){window.scrollTo(_ds.Ak(document).x,
c)});_ds.B(h)})},cU=function(a,b){var c,d,e;_ds.Va(function(f){if(c=kU(a,b.source)){d="goog_"+_ds.Mo++;c.setAttribute("name",d);var h=_ds.Bo(3);e=_ds.Pg(h,2,d);(h=b.source)&&h.postMessage(_ds.Fg(e),"*")}_ds.B(f)})},eU=function(a,b,c){var d;_ds.Va(function(e){var f=_ds.Co(_ds.Bo(8),_ds.M(b,8));d=_ds.Pg(f,6,c.toString());(f=a.source)&&f.postMessage(_ds.Fg(d),"*");_ds.B(e)})},fU=function(a,b,c){var d;_ds.Va(function(e){var f=_ds.Co(_ds.Bo(2),_ds.M(b,8));d=_ds.Pg(f,7,c.search+c.hash);(f=a.source)&&f.postMessage(_ds.Fg(d),
"*");_ds.B(e)})},gU=function(a,b,c){var d,e,f;_ds.Va(function(h){d=c.getTitle();e=new URL(c.getUrl(),b.origin);f=window.location.origin+window.location.pathname+e.search+e.hash;6===a?window.history.pushState({},d,f):window.history.replaceState({},d,f);_ds.B(h)})},hU=function(a,b){var c,d,e,f;_ds.Va(function(h){c=_ds.M(b,9);d=JSON.parse(_ds.M(b,10));"cloudtrackEvent"===c&&d?(e=d,f={eventData:e},a.dispatchEvent(new CustomEvent("devsite-analytics-observation-cloudtrack",{detail:f,bubbles:!0}))):"devsite-apix"===
c&&a.dispatchEvent(new CustomEvent("devsite-apix-observation",{detail:d,bubbles:!0}));_ds.B(h)})},iU=function(a,b){var c,d;_ds.Va(function(e){if(c=a.getUrl())d=new URL(c,b.origin),c.startsWith("#")||b.origin===d.origin&&b.pathname===d.pathname&&b.search===d.search?DevsiteApp.scrollToAnchor(d.hash,!0):DevsiteApp.fetchPage(d.href);_ds.B(e)})},kU=function(a,b){var c;Array.from(a.querySelectorAll("devsite-iframe iframe")).forEach(function(d){_ds.Zk(d)===b&&(c=d)});return c},nU=function(a){a.o=a.querySelector(".devsite-article-body");
a.o&&lU(a);a.h&&a.h.disconnect();a.m.clear();bU(a);var b=Array.from(a.querySelectorAll(".devsite-nav-title, .devsite-page-title, td > code, th > code"));if("docs"===document.body.getAttribute("layout")&&a.o){var c=Array.from(a.o.querySelectorAll("h1, h2, h3, h4, h5, h6"));b.push.apply(b,_ds.sa(c))}a.m.clear();a.m=new Set(b);if(_ds.nm().hash){b=new _ds.CG;c=_ds.p(a.m);for(var d=c.next();!d.done;d=c.next())_ds.EG(b,d.value)}else mU(a,a.m);a.dispatchEvent(new CustomEvent("devsite-content-updated",{bubbles:!0}))},
lU=function(a){"full"===document.body.getAttribute("layout")&&(a=a.o.querySelectorAll('h1[tabindex="0"],h2[tabindex="0"],h3[tabindex="0"],h4[tabindex="0"],h5[tabindex="0"],h6[tabindex="0"]'))&&Array.from(a).forEach(function(b){b.removeAttribute("tabindex")})},mU=function(a,b){a.h&&b.forEach(function(c){a.h.observe(c)})};_ds.q(aU,_ds.ci);aU.prototype.connectedCallback=function(){var a=this;this.C.listen(window,"message",function(b){return jU(a,b)});nU(this)};
aU.prototype.disconnectedCallback=function(){this.h&&this.h.disconnect();this.m.clear();_ds.Ol(this.C);_ds.Ol(this.D)};aU.prototype.Xa=function(a){var b=this;a&&([".devsite-article",".devsite-content-data","devsite-content-footer","devsite-google-survey"].forEach(function(c){_ds.ei(b,b.querySelector(c),a.querySelector(c))}),nU(this))};aU.prototype.updateContent=aU.prototype.Xa;aU.prototype.disconnectedCallback=aU.prototype.disconnectedCallback;aU.prototype.connectedCallback=aU.prototype.connectedCallback;try{window.customElements.define("devsite-content",aU)}catch(a){console.warn("devsite.app.customElement.DevsiteContent",a)};})(_ds_www);
