(function(_ds){var window=this;/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
'use strict';var sZ=function(){var a=_ds.ci.call(this)||this;a.m=new _ds.zo;a.h=new _ds.Il;qZ().then(function(){rZ(a)});return a},rZ=function(a){var b;return _ds.Va(function(c){return(b=_ds.XL.get("django_language"))?_ds.A(c,a.m.set("language_preference",b),0):c.G(0)})},uZ=function(a){_ds.Ol(a.h);var b=a.querySelector(".devsite-language-selector-select");b&&a.h.listen(b,"change",function(c){tZ(a,c)})},tZ=function(a,b){var c,d;_ds.Va(function(e){switch(e.j){case 1:return _ds.A(e,DevsiteApp.whenReady(),
2);case 2:return _ds.XL.remove("django_language"),c=b.target,_ds.XL.set("django_language",c.value,{Nb:15552E3,path:"/"}),d=document.documentElement.getAttribute("lang"),_ds.A(e,vZ(a,d,c.value),3);case 3:return _ds.A(e,rZ(a),4);case 4:var f=_ds.$o(_ds.Wi(new _ds.Hi(_ds.Ck().location.href),"hl").toString());_ds.Ck().location.assign(_ds.Yh(f));_ds.B(e)}})},vZ=function(a,b,c){var d,e;return _ds.Va(function(f){a.dispatchEvent(new CustomEvent("devsite-analytics-observation",{detail:{category:"Site-Wide Custom Events",
label:"Language Selector",action:b+" to "+c},bubbles:!0}));d={name:"change",type:"languageSelector",metadata:{"selected-language":c,"original-language":b}};e={eventData:JSON.stringify(d)};a.dispatchEvent(new CustomEvent("devsite-analytics-observation-cloudtrack",{detail:e,bubbles:!0}));_ds.B(f)})},qZ=function(){return _ds.Va(function(a){if(1==a.j)return _ds.XL.get("django_language")?a.G(0):_ds.A(a,DevsiteApp.whenReady(),3);_ds.XL.set("django_language",DevsiteApp.getLocale()||"en",{Nb:15552E3,path:"/"});
_ds.B(a)})};_ds.q(sZ,_ds.ci);sZ.prototype.connectedCallback=function(){uZ(this)};sZ.prototype.disconnectedCallback=function(){_ds.Ol(this.h)};sZ.prototype.Xa=function(a){a&&(_ds.ei(this,this.querySelector(".devsite-language-selector-menu"),a.querySelector(".devsite-language-selector-menu")),uZ(this))};sZ.prototype.updateContent=sZ.prototype.Xa;sZ.prototype.disconnectedCallback=sZ.prototype.disconnectedCallback;sZ.prototype.connectedCallback=sZ.prototype.connectedCallback;try{window.customElements.define("devsite-language-selector",sZ)}catch(a){console.warn("devsite.app.customElement.DevsiteLanguageSelector",a)};})(_ds_www);
