(function(_ds){var window=this;'use strict';var QS=function(){return(0,_ds.O)('<input type="checkbox" class="bookmark-checkbox">')},RS=function(a){var b=a.isSignedIn;a=a.Eb;var c='<devsite-dialog class="devsite-bookmark-dialog" id="devsite-bookmark-dialog"><div class="devsite-dialog-contents">';a&&(c+='<h3 class="no-link">',c=(b?c+"Create a Google Developer Profile to bookmark":c+"Sign in to bookmark")+"</h3>");c+="<p>";c=(b?a?c+"Save your frequently visited pages with a Google Developer Profile.":c+'This account is not eligible for Developer Profiles. <a href="https://developers.google.com#i%E2%80%99m_unable_to_create_a_profile_with_my_g_suite_account_why_is_that" target="_blank">Learn more</a>':
c+"You need to be signed in to save your frequently visited pages with a Google Developer Profile.")+"</p>";b&&a&&(c+="<p>Create your Google Developer Profile.</p>");c+='</div><div class="devsite-dialog-buttons">';c=b?a?c+'<button class="button-primary create-profile">\u0421\u043e\u0437\u0434\u0430\u0442\u044c \u043f\u0440\u043e\u0444\u0438\u043b\u044c':c+'<button class="button-primary change-account">\u0421\u043c\u0435\u043d\u0438\u0442\u044c \u0430\u043a\u043a\u0430\u0443\u043d\u0442':c+'<button class="button button-primary sign-in-button">\u0412\u043e\u0439\u0442\u0438';
return(0,_ds.O)(c+'</button><button class="button devsite-dialog-close">\u0417\u0430\u043a\u0440\u044b\u0442\u044c</button></div></devsite-dialog>')},SS=function(a){var b=a.hb;a='<devsite-dialog class="devsite-bookmark-dialog" id="devsite-bookmark-create-profile-dialog"><div class="create-profile-spinner"><devsite-spinner size="48"></devsite-spinner></div><div class="devsite-dialog-contents"><h3 class="no-link">Would you like to receive emails regarding new features, events, badges, content, and research opportunities?</h3><input type="checkbox" id="devsite-bookmark-create-profile-email-opt-in"><label for="devsite-bookmark-create-profile-email-opt-in">Yes, sign me up for Google Developer emails.</label><p class="account-note">';
b='By creating a Developer Profile, you agree to the <a href="'+(_ds.T(_ds.Tj(b))+'">Content Policy</a>. Google\'s <a href="https://policies.google.com/terms">Terms of Service</a> and <a href="https://policies.google.com/privacy">Privacy Policy</a> apply to your use of this service. The name on your Google Account will be used in your Google Developer Profile. It may appear where you contribute and can be changed at any time.');a=a+b+'</p></div><div class="devsite-dialog-buttons"><button class="button-primary create-profile">Create Profile';
a+='</button><button class="button devsite-dialog-close">';a+="\u0417\u0430\u043a\u0440\u044b\u0442\u044c";a+="</button></div></devsite-dialog>";return(0,_ds.O)(a)},TS=function(a){a='<devsite-dialog class="devsite-bookmark-dialog" id="devsite-bookmark-error-dialog"><div class="devsite-dialog-contents"><h3 class="no-link">Something went wrong</h3><p>'+(_ds.R(a.error)+'</p></div><div class="devsite-dialog-buttons"><button class="button devsite-dialog-close">');return(0,_ds.O)(a+"\u0417\u0430\u043a\u0440\u044b\u0442\u044c</button></div></devsite-dialog>")},
US=function(){var a=_ds.ci.call(this,["devsite-snackbar","devsite-dialog"])||this;a.eventHandler=new _ds.Il;a.D=null;a.o=null;a.F=null;a.h=null;a.m=null;a.C=!1;return a},WS=function(a){a.eventHandler.listen(a,"change",function(){VS(a)})},VS=function(a){return _ds.N(a,function c(){var d=this,e,f,h,k,l;return _ds.F(c,function(m){switch(m.j){case 1:d.toggleAttribute("saved");XS(d);if(!d.C){YS(d,"Page unsaved.");m.G(2);break}return _ds.A(m,(0,_ds.Ev)("/saved-pages",void 0,void 0,!1,!0),3);case 3:e=m.h,
YS(d,"Page saved.","View Saved Pages",e);case 2:return _ds.A(m,(0,_ds.Bp)(),4);case 4:return f=m.h,_ds.A(m,f.isSignedIn(),5);case 5:h=m.h;k=!0;if(!h){m.G(6);break}return _ds.A(m,d.Eb(),7);case 7:k=m.h;case 6:if(!k){m.G(8);break}return _ds.A(m,d.Z(),9);case 9:l=m.h;if(!l){m.G(8);break}return _ds.A(m,ZS(d,l),11);case 11:return m.return();case 8:d.F=$S(d,h,k),d.F.setAttribute("open",""),_ds.B(m)}})})},YS=function(a,b,c,d){a.dispatchEvent(new CustomEvent("devsite-show-custom-snackbar-msg",{detail:{msg:b,
linkText:c,href:null===d||void 0===d?void 0:d.href,showClose:!1},bubbles:!0}))},XS=function(a){var b;if(a.o){var c=(a.o.checked=a.C)?"Remove bookmark":"Add bookmark";a.setAttribute("data-title",c);null===(b=a.o)||void 0===b?void 0:b.setAttribute("aria-label",c)}},$S=function(a,b,c){var d=document.body.querySelector("#devsite-bookmark-dialog");d||(d=_ds.xl(RS,{isSignedIn:b,Eb:c}),document.body.appendChild(d),(b=d.querySelector(".create-profile"))&&a.eventHandler.listen(b,"click",function(){return _ds.N(a,
function f(){var h=this;return _ds.F(f,function(k){if(1==k.j)return null===d||void 0===d?void 0:d.removeAttribute("open"),_ds.A(k,aT(h),2);h.h=k.h;h.h.setAttribute("open","");_ds.B(k)})})}),(b=d.querySelector(".sign-in-button"))&&a.eventHandler.listen(b,"click",function(e){return _ds.N(a,function h(){var k,l;return _ds.F(h,function(m){if(1==m.j)return e.preventDefault(),e.stopPropagation(),k=new _ds.Hi(_ds.nm().href),k.h.add("bookmark",!0),_ds.om(k.toString(),!0,!1),_ds.A(m,(0,_ds.Bp)(),2);l=m.h;
return _ds.A(m,l.signIn(),0)})})}),(b=d.querySelector(".change-account"))&&a.eventHandler.listen(b,"click",function(e){return _ds.N(a,function h(){var k,l;return _ds.F(h,function(m){if(1==m.j)return e.preventDefault(),e.stopPropagation(),k=new _ds.Hi(_ds.nm().href),k.h.add("bookmark",!0),_ds.om(k.toString(),!0,!1),_ds.A(m,(0,_ds.Bp)(),2);l=m.h;return _ds.A(m,l.changeAccount(),0)})})}),(b=d.querySelector(".devsite-dialog-close"))&&a.eventHandler.listen(b,"click",function(){a.toggleAttribute("saved");
bT(a,"Callout Profile dismissed")}));return d},aT=function(a){return _ds.N(a,function c(){var d=this,e,f,h,k,l;return _ds.F(c,function(m){if(1==m.j)return e=d,bT(d,"Callout Profile displayed"),(f=document.body.querySelector("#devsite-bookmark-create-profile-dialog"))?m.G(2):_ds.A(m,(0,_ds.Cv)(),3);2!=m.j&&(h=m.h.href,f=_ds.xl(SS,{hb:h}),document.body.appendChild(f),(k=f.querySelector(".create-profile"))&&d.eventHandler.listen(k,"click",function(){e.createProfile()}),(l=f.querySelector(".devsite-dialog-close"))&&
d.eventHandler.listen(l,"click",function(){e.toggleAttribute("saved");bT(e,"Callout Profile dismissed")}));return m.return(f)})})},cT=function(a,b){bT(a,"Callout Profile error");a=document.body.querySelector("#devsite-bookmark-error-dialog");a||(a=_ds.xl(TS,{error:b}),document.body.appendChild(a));return a},ZS=function(a,b){return _ds.N(a,function d(){var e,f=this,h,k,l,m;return _ds.F(d,function(n){switch(n.j){case 1:if(null===b||void 0===b||!b.profileId)return n.return();e="SAVE_STATE_UNKNOWN";e=
f.C?"SAVED":"UNSAVED";h=_ds.nm().href;_ds.C(n,2);return _ds.A(n,(0,_ds.Lv)(h),4);case 4:h=n.h;_ds.D(n,3);break;case 2:_ds.E(n);case 3:return k=new _ds.tv,_ds.C(n,5),_ds.A(n,k.Ge({path:h,status:e,profileId:b.profileId}),7);case 7:_ds.D(n,6);break;case 5:_ds.E(n),f.m=cT(f,"There was an issue saving the page."),f.m.setAttribute("open",""),f.toggleAttribute("saved");case 6:return l=document.querySelector("devsite-user#devsite-user"),_ds.A(n,(0,_ds.Ev)("/saved-pages",null===b||void 0===b?void 0:b.profileId,
null===b||void 0===b?void 0:b.vanityId,!1,!0),8);case 8:return m=n.h,_ds.A(n,null===l||void 0===l?void 0:l.Ke("view-bookmarked-pages",m),0)}})})},dT=function(a){return _ds.N(a,function c(){var d,e=this,f,h,k,l,m,n;return _ds.F(c,function(r){switch(r.j){case 1:d=new _ds.Hi(_ds.nm().href);if(!_ds.gj(d.h,"bookmark")){r.G(2);break}return _ds.A(r,VS(e),3);case 3:return d.h.remove("bookmark"),_ds.om(d.toString(),!0,!1),r.return();case 2:return _ds.A(r,DevsiteApp.whenReady(),4);case 4:return _ds.A(r,DevsiteApp.isSignedIn(),
5);case 5:return(f=r.h)?_ds.A(r,e.Z(),6):r.return();case 6:h=r.h;if(null===h||void 0===h||!h.profileId)return r.return();k=_ds.nm().href;_ds.C(r,7);return _ds.A(r,(0,_ds.Lv)(k),9);case 9:k=r.h;_ds.D(r,8);break;case 7:_ds.E(r);case 8:return l=(null===h||void 0===h?void 0:h.profileId)||"",m=new _ds.tv,_ds.C(r,10),_ds.A(r,m.getPath({path:k,profileId:l}),12);case 12:n=r.h;if("SAVED"===(null===n||void 0===n?void 0:n.saveStatus))return e.setAttribute("saved",""),r.return();_ds.D(r,0);break;case 10:_ds.E(r),
_ds.B(r)}})})},bT=function(a,b){a.dispatchEvent(new CustomEvent("devsite-analytics-observation",{detail:{category:"Site-Wide Custom Events",action:b,label:"Saving Widget Callout"},bubbles:!0}))};_ds.q(US,_ds.ci);_ds.g=US.prototype;
_ds.g.connectedCallback=function(){var a,b;return _ds.N(this,function d(){var e,f=this;return _ds.F(d,function(h){if(1==h.j)return e=document.body.querySelector(".devsite-page-title,.devsite-playlist-title,.devsite-quiz-title,[layout=docs] .devsite-article h1:first-of-type"),e?e&&f.previousElementSibling!==e?(null===(a=e.parentElement)||void 0===a?void 0:a.insertBefore(f,e.nextSibling),h.return()):_ds.A(h,dT(f),2):(f.remove(),h.return());_ds.wl(f,QS);f.D=document.body.querySelector(".devsite-article");null===
(b=f.D)||void 0===b?void 0:b.setAttribute("has-bookmark","");f.o=f.querySelector(".bookmark-checkbox");XS(f);WS(f);_ds.B(h)})})};_ds.g.disconnectedCallback=function(){var a;_ds.Ol(this.eventHandler);_ds.Nk(this.F);_ds.Nk(this.h);_ds.Nk(this.m);this.o=null;null===(a=this.D)||void 0===a?void 0:a.removeAttribute("has-bookmark")};_ds.g.attributeChangedCallback=function(a,b,c){"saved"===a&&(this.C=null!==c)};
_ds.g.createProfile=function(){var a,b,c,d,e,f;return _ds.N(this,function k(){var l,m,n=this,r,t,u,v,w;return _ds.F(k,function(y){switch(y.j){case 1:return l=document.querySelector("devsite-user#devsite-user"),_ds.A(y,null===l||void 0===l?void 0:l.getAccountName(),2);case 2:if(m=y.h){y.G(3);break}return _ds.A(y,null===l||void 0===l?void 0:l.getAccountEmail(),4);case 4:(m=y.h)&&(m=m.charAt(0));case 3:if(!m)return null===(a=n.h)||void 0===a?void 0:a.removeAttribute("open"),n.m=cT(n,"There was an issue getting your account information."),
n.m.setAttribute("open",""),n.toggleAttribute("saved"),y.return();r=null===(b=n.h)||void 0===b?void 0:b.querySelector("#devsite-bookmark-create-profile-email-opt-in");t=!(!r||!r.checked);null===(c=n.h)||void 0===c?void 0:c.classList.add("loading");u=new _ds.vv;_ds.C(y,5);return _ds.A(y,_ds.xv(u,m,t,!0),7);case 7:return bT(n,"Callout Profile created"),null===(d=n.h)||void 0===d?void 0:d.removeAttribute("open"),_ds.A(y,n.Z(),8);case 8:v=y.h;if(!v){y.G(9);break}return _ds.A(y,ZS(n,v),9);case 9:_ds.D(y,
6);break;case 5:w=_ds.E(y),null===(e=n.h)||void 0===e?void 0:e.removeAttribute("open"),n.m=cT(n,""+w),n.m.setAttribute("open",""),n.toggleAttribute("saved");case 6:null===(f=n.h)||void 0===f?void 0:f.classList.remove("loading"),_ds.B(y)}})})};
_ds.g.Eb=function(){var a;return _ds.N(this,function c(){var d,e,f,h;return _ds.F(c,function(k){switch(k.j){case 1:return _ds.A(k,(0,_ds.Bp)(),2);case 2:return d=k.h,_ds.A(k,d.isSignedIn(),3);case 3:e=k.h;if(!e)return k.return(!1);f=new _ds.rv;h=null;_ds.C(k,4);return _ds.A(k,f.Ta(),6);case 6:h=k.h;_ds.D(k,5);break;case 4:_ds.E(k);case 5:return k.return("ELIGIBILITY_ELIGIBLE"===(null===(a=null===h||void 0===h?void 0:h.createProfile)||void 0===a?void 0:a.status))}})})};
_ds.g.Z=function(){return _ds.N(this,function b(){var c=this,d,e,f;return _ds.F(b,function(h){switch(h.j){case 1:return _ds.A(h,c.Eb(),2);case 2:d=h.h;if(!d)return h.return(null);e=new _ds.vv;f=null;_ds.C(h,3);return _ds.A(h,e.Z(),5);case 5:f=h.h;_ds.D(h,4);break;case 3:_ds.E(h);case 4:return h.return(f)}})})};_ds.ja.Object.defineProperties(US,{observedAttributes:{configurable:!0,enumerable:!0,get:function(){return["saved"]}}});try{window.customElements.define("devsite-bookmark",US)}catch(a){console.warn("Unrecognized DevSite custom element - DevsiteBookmark",a)};})(_ds_www);
