(function(_ds){var window=this;'use strict';var lS=function(a,b){a.href=_ds.Yh(b)},mS=function(){return(0,_ds.O)('<button class="devsite-book-nav-toggle" aria-haspopup="menu"><span class="material-icons devsite-book-nav-toggle-icon"></span></button>')},nS=function(){return(0,_ds.O)('<div class="devsite-book-nav-blur"></div>')},pS=function(){var a=_ds.ci.call(this)||this;a.o=!1;a.m=null;a.eventHandler=new _ds.Il;a.H=function(){};a.C=new Set;a.J=!1;a.background=document.createElement("div");a.background.classList.add("devsite-book-nav-bg");
a.h=_ds.xl(mS);a.D=_ds.xl(nS);a.K=new Promise(function(b){a.H=b});a.F=new _ds.Ln(function(){a.o&&oS(a)},20);return a},rS=function(a,b,c){c=void 0===c?!0:c;b=Array.from((void 0===b?a:b).querySelectorAll(".devsite-nav-title"));a.C=new Set(b);if(!_ds.nm().hash&&c)qS(a,a.C);else for(c=new _ds.CG,a=_ds.p(a.C),b=a.next();!b.done;b=a.next())_ds.EG(c,b.value)},qS=function(a,b){_ds.N(a,function d(){var e=this,f,h,k,l,m,n,r;return _ds.F(d,function(t){if(1==t.j)return f=e,e.o?_ds.A(t,(0,_ds.Bp)(),2):t.return();
h=t.h;k=new _ds.CG;l=function(u){u=u.target;_ds.EG(k,u);f.C.delete(u);h.unregisterIntersectionForElement(u)};m=_ds.p(b);for(n=m.next();!n.done;n=m.next()){r=n.value;try{h.registerIntersectionForElement(r,l)}catch(u){l({target:r})}}_ds.B(t)})})},oS=function(a){var b=0<a.querySelectorAll(".devsite-nav-item").length,c=document.querySelector("#devsite-hamburger-menu");c&&(b?c.removeAttribute("visually-hidden"):_ds.di(a,"visually-hidden","",c))},wS=function(a){a.eventHandler.listen(a,"click",function(b){var c;
if(!b.defaultPrevented){var d=b.target;"devsite-close-nav"===d.getAttribute("id")&&(b.preventDefault(),b.stopPropagation(),a.scrollTop=0,a.hasAttribute("top-level-nav")?a.dispatchEvent(new CustomEvent("devsite-sitemask-hide",{bubbles:!0})):_ds.di(a,"top-level-nav",""));if(d.hasAttribute("menu")){var e=d.getAttribute("menu");e&&sS(a,e)&&(b.preventDefault(),b.stopPropagation(),a.scrollTop=0,a.removeAttribute("top-level-nav"))}if(!(d.classList.contains("devsite-nav-toggle")||d.classList.contains("devsite-nav-title-no-path")||
(null===(c=d.parentElement)||void 0===c?0:c.classList.contains("devsite-nav-title-no-path")))){a.m&&(b=a.m.querySelector("[menu=_book]"))&&b.contains(d)&&a.dispatchEvent(new CustomEvent("devsite-sitemask-hide",{bubbles:!0}));var f;d instanceof Element&&d.matches("a.devsite-nav-title")?f=d:f=_ds.kl(d,"a","devsite-nav-title");f&&!f.classList.contains("devsite-nav-has-children")&&a.dispatchEvent(new CustomEvent("devsite-sitemask-hide",{bubbles:!0}))}}});a.eventHandler.listen(a,[tS,"focusin"],function(b){return void uS(a,
b)});a.eventHandler.listen(document.body,"devsite-sitemask-hidden",function(){a.m&&(sS(a,"_book")?a.removeAttribute("top-level-nav"):_ds.di(a,"top-level-nav",""))});a.eventHandler.listen(document.body,"devsite-page-loaded",function(){return void a.F.ya()});a.eventHandler.listen(a,"devsite-content-updated",function(){a.F.ya()});a.eventHandler.listen(a,"scroll",function(){_ds.di(a,"user-scrolled","")});a.eventHandler.listen(a.h,"click",function(){vS(a)})},sS=function(a,b){var c=!1;if(a.m)for(var d=
_ds.p(a.m.querySelectorAll("[menu]")),e=d.next();!e.done;e=d.next())e=e.value,e.getAttribute("menu")===b?(e.removeAttribute("hidden"),c=!0):_ds.di(a,"hidden","",e);return c},uS=function(a,b){b.defaultPrevented||(b=_ds.jl(b.target,function(c){return c instanceof HTMLAnchorElement&&c.hasAttribute("href")||c===a},!0),b!==a&&lS(b,_ds.$o(_ds.um(b.href).href)))},yS=function(a){return _ds.N(a,function c(){var d=this;return _ds.F(c,function(e){switch(e.j){case 1:if(!d.o)return e.return();d.removeAttribute("user-scrolled");
return _ds.A(e,_ds.Fm(),2);case 2:return _ds.A(e,xS(d),3);case 3:return _ds.A(e,d.K,4);case 4:return _ds.A(e,(0,_ds.Bp)(),5);case 5:return _ds.A(e,_ds.Fm(),6);case 6:return _ds.A(e,xS(d),0)}})})},zS=function(a,b){(b=void 0===b?a:b)||(b=a);var c=_ds.p(b.querySelectorAll(".devsite-nav-active"));for(a=c.next();!a.done;a=c.next())a.value.classList.remove("devsite-nav-active");a=_ds.Km(_ds.nm().pathname);a='[href="'+_ds.um(a).href+'"], [href="'+a+'"],\n        [alt-paths~="'+a+'"]';b=_ds.p(b.querySelectorAll(a));
for(a=b.next();!a.done;a=b.next())a.value.classList.add("devsite-nav-active")},AS=function(a,b){(b=void 0===b?a:b)||(b=a);var c=b.querySelector(".devsite-mobile-nav-bottom");if(c)for(var d=c.querySelector(".devsite-nav-active");d&&d.parentElement&&d.parentElement!==b;)d.hasAttribute("collapsed")&&(d.removeAttribute("animatable"),_ds.Ml(a.eventHandler,d,"devsite-expandable-nav-transition-end",function(){d&&_ds.di(a,"animatable","",d)}),d.removeAttribute("collapsed")),d=d.parentElement},xS=function(a){return _ds.N(a,
function c(){var d=this,e;return _ds.F(c,function(f){if(1==f.j)return d.o&&d.m?_ds.A(f,(0,_ds.Bp)(),2):f.return();if(4!=f.j)return(e=d.m.querySelector(".devsite-nav-active"))?d.hasAttribute("user-scrolled")?f.G(4):_ds.A(f,BS(d,e),4):f.G(0);_ds.di(d,"animatable","");_ds.B(f)})})},BS=function(a,b){return _ds.N(a,function d(){var e=this,f,h;return _ds.F(d,function(k){if(1==k.j){if(!e.o)return k.return();f=e.hasAttribute("user-scrolled");h=_ds.ao(b,e,!0);e.scrollTop=h.y;return _ds.A(k,_ds.Fm(),2)}f&&
_ds.di(e,"user-scrolled","");_ds.B(k)})})},CS=function(a){return _ds.N(a,function c(){var d,e=this,f,h,k;return _ds.F(c,function(l){if(1==l.j)return _ds.A(l,(0,_ds.Bp)(),2);d=l.h;f=_ds.p(e.C);for(h=f.next();!h.done;h=f.next())k=h.value,d.unregisterIntersectionForElement(k);_ds.B(l)})})},vS=function(a){_ds.N(a,function c(){var d,e,f=this;return _ds.F(c,function(h){if(1==h.j)return e=(d=document.documentElement.scrollHeight-document.documentElement.clientHeight)?document.documentElement.scrollTop/d:
0,f.hasAttribute("collapsed")?(_ds.di(f,"aria-expanded","true",f.h),_ds.di(f,"aria-label","Hide side navigation",f.h),_ds.di(f,"data-title","Hide side navigation",f.h),f.removeAttribute("collapsed"),DS(f,"Expanded book nav")):(f.h.removeAttribute("aria-expanded"),_ds.di(f,"aria-label","Show side navigation",f.h),_ds.di(f,"data-title","Show side navigation",f.h),_ds.di(f,"collapsed",""),DS(f,"Collapsed book nav")),_ds.A(h,_ds.Fm(),2);d=document.documentElement.scrollHeight-document.documentElement.clientHeight;
document.documentElement.scrollTop=Math.round(e*d);_ds.B(h)})})},DS=function(a,b){a.dispatchEvent(new CustomEvent("devsite-analytics-observation",{detail:{category:"Site-Wide Custom Events",action:"click",label:b},bubbles:!0}))};var ES=_ds.ra(["animatable"]),FS=_ds.ra(["aria-expanded"]),GS=_ds.ra(["aria-label"]),HS=_ds.ra(["collapsed"]),IS=_ds.ra(["data-title"]),JS=_ds.ra(["fixed"]),KS=_ds.ra(["has-book-nav"]),LS=_ds.ra(["hidden"]),MS=_ds.ra(["role"]),NS=_ds.ra(["top-level-nav"]),OS=_ds.ra(["user-scrolled"]),PS=_ds.ra(["visually-hidden"]),tS="onpointerover"in window?"pointerover":"mouseover";_ds.q(pS,_ds.ci);_ds.g=pS.prototype;
_ds.g.connectedCallback=function(){var a,b;return _ds.N(this,function d(){var e=this,f;return _ds.F(d,function(h){if(1==h.j)return e.o=!0,e.O(e.j(ES),e.j(FS),e.j(GS),e.j(HS),e.j(IS),e.j(JS),e.j(KS),e.j(LS),e.j(MS),e.j(NS),e.j(OS),e.j(PS)),_ds.di(e,"role","menu"),_ds.Kk(e.background,e),e.hasAttribute("hidden")&&(_ds.di(e,"hidden","",e.h),_ds.di(e,"hidden","",e.D)),_ds.A(h,(0,_ds.Bp)(),2);if(3!=h.j)return f=h.h,e.J=f.hasFlagAccess(150),e.J&&(null===(a=e.parentElement)||void 0===a?void 0:a.insertBefore(e.h,
e.nextSibling),_ds.di(e,"aria-label","Hide side navigation",e.h),_ds.di(e,"data-title","Hide side navigation",e.h),_ds.di(e,"aria-expanded","true",e.h),null===(b=e.parentElement)||void 0===b?void 0:b.insertBefore(e.D,e.nextSibling)),oS(e),wS(e),_ds.A(h,e.init(),3);rS(e);_ds.B(h)})})};
_ds.g.disconnectedCallback=function(){this.o=!1;_ds.Ol(this.eventHandler);CS(this);this.C.clear();var a=document.querySelector("#devsite-hamburger-menu");a&&_ds.di(this,"visually-hidden","",a);a=_ds.p([this.background,this.h,this.D]);for(var b=a.next();!b.done;b=a.next())(b=b.value)&&_ds.Nk(b);this.removeAttribute("animatable");document.body.style.removeProperty("--devsite-js-book-nav-scrollbar-width")};
_ds.g.attributeChangedCallback=function(a){"hidden"===a&&this.dispatchEvent(new CustomEvent(this.hasAttribute("hidden")?"devsite-element-hidden":"devsite-element-visible",{bubbles:!0}));if("hidden"===a||"collapsed"===a){var b=document.querySelector(".devsite-main-content");b&&(this.hasAttribute("collapsed")||this.hasAttribute("hidden")?b.removeAttribute("has-book-nav"):_ds.di(this,"has-book-nav","",b))}if("fixed"===a||"hidden"===a||"collapsed"===a){b=this.hasAttribute(a);for(var c=_ds.p([this.background,
this.h,this.D]),d=c.next();!d.done;d=c.next())(d=d.value)&&(b?_ds.di(this,a,"",d):d.removeAttribute(a))}"fixed"===a&&this.H()};
_ds.g.init=function(a){a=void 0===a?!0:a;return _ds.N(this,function c(){var d=this,e,f,h;return _ds.F(c,function(k){if(1==k.j){if(!d.o)return k.return();document.body.style.setProperty("--devsite-js-book-nav-scrollbar-width",d.offsetWidth-d.clientWidth+"px");d.m=d.querySelector(".devsite-mobile-nav-bottom");!d.hasAttribute("hidden")&&d.m&&d.m.querySelector(".devsite-nav-active")||_ds.di(d,"animatable","");_ds.di(d,"top-level-nav","");d.m&&d.m.querySelector("[menu=_book]")&&d.removeAttribute("top-level-nav");
0===d.children.length&&_ds.di(d,"hidden","");if(d.background)for(e=_ds.p(["hidden","fixed"]),f=e.next();!f.done;f=e.next())h=f.value,d.hasAttribute(h)&&_ds.di(d,h,"",d.background);return!d.hasAttribute("hidden")&&a?(zS(d),AS(d),_ds.A(k,yS(d),0)):_ds.A(k,_ds.Fm(),4)}return _ds.A(k,xS(d),0)})})};
_ds.g.Xa=function(a){return _ds.N(this,function c(){var d=this,e;return _ds.F(c,function(f){switch(f.j){case 1:if(!a){_ds.Jk(d);f.G(2);break}d.removeAttribute("animatable");e=a.querySelector("nav")||null;zS(d,e);AS(d,e);if(!e){f.G(3);break}return _ds.A(f,CS(d),4);case 4:d.C.clear(),rS(d,e,!1);case 3:_ds.ei(d,d.querySelector("nav"),e);case 2:return _ds.A(f,_ds.Fm(),5);case 5:return _ds.A(f,d.init(!1),0)}})})};
_ds.ja.Object.defineProperties(pS,{observedAttributes:{configurable:!0,enumerable:!0,get:function(){return["collapsed","fixed","hidden"]}}});pS.prototype.updateContent=pS.prototype.Xa;pS.prototype.attributeChangedCallback=pS.prototype.attributeChangedCallback;pS.prototype.disconnectedCallback=pS.prototype.disconnectedCallback;pS.prototype.connectedCallback=pS.prototype.connectedCallback;try{window.customElements.define("devsite-book-nav",pS)}catch(a){console.warn("Unrecognized DevSite custom element - DevsiteBookNav",a)};})(_ds_www);
