(function(_ds){var window=this;'use strict';var DT=function(a,b){for(var c=1;c<arguments.length;c++){var d=arguments[c];if(_ds.gb(d)){var e=a.length||0,f=d.length||0;a.length=e+f;for(var h=0;h<f;h++)a[e+h]=d[h]}else a.push(d)}},ET=function(){var a=new _ds.eG;DT(a.L,"data-devsite-credential-type data-modal-dialog-id data-scope data-terminal-prefix data-title data-type".split(" "));return a},FT=function(){var a=ET();["devsite-var"].forEach(function(b){this.K.push(b)},a);return a},GT=function(){var a='<div class="devsite-code-buttons-container" role="group" aria-label="'+
_ds.wj("\u041a\u043d\u043e\u043f\u043a\u0438 \u0443\u043f\u0440\u0430\u0432\u043b\u0435\u043d\u0438\u044f");return(0,_ds.O)(a+'"></div>')},HT=function(a){a=a.label;return(0,_ds.O)('<button type="button" class="gc-analytics-event material-icons devsite-icon-code-dark devsite-toggle-dark" data-category="Site-Wide Custom Events" data-label="Dark Code Toggle" track-type="exampleCode" track-name="darkCodeToggle" aria-label="'+_ds.T(a)+'" data-title="'+_ds.T(a)+'"></button>')},IT=function(a){a=a.label;
return(0,_ds.O)('<button type="button" class="gc-analytics-event material-icons devsite-icon-code-light devsite-toggle-light" data-category="Site-Wide Custom Events" data-label="Light Code Toggle" track-type="exampleCode" track-name="lightCodeToggle" aria-label="'+_ds.T(a)+'" data-title="'+_ds.T(a)+'"></button>')},JT=function(a){var b=a.label;return(0,_ds.O)('<button type="button" class="gc-analytics-event material-icons devsite-icon-copy" data-category="Site-Wide Custom Events" data-label="'+_ds.T(a.Tp)+
'" track-type="exampleCode" track-name="clickToCopy" aria-label="'+_ds.T(b)+'" data-title="'+_ds.T(b)+'"></button>')},KT=function(a){a=a.label;return(0,_ds.O)('<button type="button" class="gc-analytics-event material-icons devsite-icon-code" data-category="jsfiddle" data-label="" track-type="exampleCode" track-name="jsfiddle" aria-label="'+_ds.T(a)+'" data-title="'+_ds.T(a)+'"></button>')},LT=function(){var a=_ds.ci.call(this,["devsite-snackbar"])||this;a.h=null;a.o=null;a.K="";a.D=null;a.m=new _ds.Il;
a.L=!1;a.C=null;a.F=null;a.M=new _ds.On;a.R=new _ds.iG(_ds.oG(FT()));a.H=null;a.J=new _ds.Tl;return a},MT=function(a){Array.from(a.getElementsByClassName("prettyprint")).forEach(function(b){b.classList.remove("prettyprint");var c=(c=b.className.match(/\blang(?:uage)?-([\w.]+)(?!\S)/))?c[1]:void 0;c=window.prettyPrintOne(b.innerHTML,c);c=a.R.h(c);_ds.Bd(b,c);b.getElementsByTagName("strong").length&&b.classList.add("devsite-code-highlight")})},NT=function(a){var b=a.getElementsByTagName("pre")[0];if(b){if(b.classList.contains("devsite-disable-click-to-copy")||
b.hasAttribute("no-copy")||!b.classList.contains("devsite-click-to-copy")&&!b.classList.contains("prettyprint")&&!b.classList.contains("devsite-terminal"))a.setAttribute("no-copy",""),b.classList.remove("devsite-disable-click-to-copy"),b.removeAttribute("no-copy");a.setAttribute("data-copy-event-label",b.getAttribute("data-copy-event-label")||"");b.classList.remove("devsite-click-to-copy");b=b.getAttribute("data-label");a.K=b?"\u0421\u043a\u043e\u043f\u0438\u0440\u043e\u0432\u0430\u0442\u044c \u043f\u0440\u0438\u043c\u0435\u0440 \u043a\u043e\u0434\u0430: "+
b:"\u0421\u043a\u043e\u043f\u0438\u0440\u043e\u0432\u0430\u0442\u044c \u043f\u0440\u0438\u043c\u0435\u0440 \u043a\u043e\u0434\u0430"}var c=a.querySelector(".devsite-enable-open-in-jsfiddle,.devsite-jsfiddle-code-sample");c&&(a.setAttribute("js-fiddle",""),c.classList.remove("devsite-enable-open-in-jsfiddle"),c.classList.add("devsite-jsfiddle-code-sample"));a.hasAttribute("js-fiddle")&&c&&["scope","jsfiddle-title","jsfiddle-wrap","jsfiddle-label"].forEach(function(d){c.hasAttribute("data-"+d)&&(a.setAttribute(d,
c.getAttribute("data-"+d)),c.removeAttribute("data-"+d))})},OT=function(a){var b,c;return _ds.Va(function(d){if(1==d.j){b=Array.from(a.querySelector("pre:not(.devsite-copy-hide)").childNodes);_ds.pI(document.body,b);if(!a.H)return d.G(0);c=new _ds.On;a.o.setAttribute("aria-label","\u041f\u0440\u0438\u043c\u0435\u0440 \u043a\u043e\u0434\u0430 \u0441\u043a\u043e\u043f\u0438\u0440\u043e\u0432\u0430\u043d \u0432 \u0431\u0443\u0444\u0435\u0440 \u043e\u0431\u043c\u0435\u043d\u0430");_ds.Ml(a.m,a.H,_ds.em,
function(){c.resolve()});return _ds.A(d,c.promise,3)}_ds.Ml(a.m,a.H,_ds.em,function(){a.o.setAttribute("aria-label",a.K)});_ds.B(d)})},PT=function(a){a.D&&a.m.listen(a.D,"click",function(){return void a.setAttribute("dark-code","")});a.F&&a.m.listen(a.F,"click",function(){return void a.removeAttribute("dark-code")});a.o&&a.m.listen(a.o,"click",function(){return void OT(a)});a.C&&a.m.listen(a.C,"click",function(){var b={title:a.getAttribute("jsfiddle-title")||"\u041f\u0440\u0438\u043c\u0435\u0440 \u043a\u043e\u0434\u0430",
wrap:a.getAttribute("jsfiddle-wrap")||"b",description:""},c=a.getAttribute("scope");c?_ds.CI(c,b):_ds.BI([a],b)})};/*
 Copyright (C) 2006 Google Inc.

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

      http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
*/
window.PR_SHOULD_USE_CONTINUATION=!0;window.PR_TAB_WIDTH=8;window.PR_normalizedHtml=void 0;window.PR=void 0;window.prettyPrintOne=void 0;window.prettyPrint=void 0;window._pr_isIE6=function(){var a=navigator&&navigator.userAgent&&navigator.userAgent.match(/\bMSIE ([678])\./);a=a?+a[1]:!1;window._pr_isIE6=function(){return a};return a};
(function(){function a(ea){return ea.replace(t,"&amp;").replace(u,"&lt;").replace(v,"&gt;")}function b(ea,X,ma){switch(ea.nodeType){case 1:var ka=ea.tagName.toLowerCase();X.push("<",ka);var wa=ea.attributes,Ia=wa.length;if(Ia){if(ma){for(var Ka=[],la=Ia;0<=--la;)Ka[la]=wa[la];Ka.sort(function(Ga,Wa){return Ga.name<Wa.name?-1:Ga.name===Wa.name?0:1});wa=Ka}for(la=0;la<Ia;++la)Ka=wa[la],Ka.specified&&X.push(" ",Ka.name.toLowerCase(),'="',Ka.value.replace(t,"&amp;").replace(u,"&lt;").replace(v,"&gt;").replace(w,
"&quot;"),'"')}X.push(">");for(wa=ea.firstChild;wa;wa=wa.nextSibling)b(wa,X,ma);!ea.firstChild&&/^(?:br|link|img)$/.test(ka)||X.push("</",ka,">");break;case 3:case 4:X.push(a(ea.nodeValue))}}function c(ea){function X(La){if("\\"!==La.charAt(0))return La.charCodeAt(0);switch(La.charAt(1)){case "b":return 8;case "t":return 9;case "n":return 10;case "v":return 11;case "f":return 12;case "r":return 13;case "u":case "x":return parseInt(La.substring(2),16)||La.charCodeAt(1);case "0":case "1":case "2":case "3":case "4":case "5":case "6":case "7":return parseInt(La.substring(1),
8);default:return La.charCodeAt(1)}}function ma(La){if(32>La)return(16>La?"\\x0":"\\x")+La.toString(16);La=String.fromCharCode(La);if("\\"===La||"-"===La||"["===La||"]"===La)La="\\"+La;return La}function ka(La){var Ma=La.substring(1,La.length-1).match(RegExp("\\\\u[0-9A-Fa-f]{4}|\\\\x[0-9A-Fa-f]{2}|\\\\[0-3][0-7]{0,2}|\\\\[0-7]{1,2}|\\\\[\\s\\S]|-|[^-\\\\]","g"));La=[];for(var Aa=[],za="^"===Ma[0],Ja=za?1:0,jb=Ma.length;Ja<jb;++Ja){var Xa=Ma[Ja];switch(Xa){case "\\B":case "\\b":case "\\D":case "\\d":case "\\S":case "\\s":case "\\W":case "\\w":La.push(Xa);
continue}Xa=X(Xa);if(Ja+2<jb&&"-"===Ma[Ja+1]){var ub=X(Ma[Ja+2]);Ja+=2}else ub=Xa;Aa.push([Xa,ub]);65>ub||122<Xa||(65>ub||90<Xa||Aa.push([Math.max(65,Xa)|32,Math.min(ub,90)|32]),97>ub||122<Xa||Aa.push([Math.max(97,Xa)&-33,Math.min(ub,122)&-33]))}Aa.sort(function(ec,Vd){return ec[0]-Vd[0]||Vd[1]-ec[1]});Ma=[];Xa=[NaN,NaN];for(Ja=0;Ja<Aa.length;++Ja)jb=Aa[Ja],jb[0]<=Xa[1]+1?Xa[1]=Math.max(Xa[1],jb[1]):Ma.push(Xa=jb);Aa=["["];za&&Aa.push("^");Aa.push.apply(Aa,La);for(Ja=0;Ja<Ma.length;++Ja)jb=Ma[Ja],
Aa.push(ma(jb[0])),jb[1]>jb[0]&&(jb[1]+1>jb[0]&&Aa.push("-"),Aa.push(ma(jb[1])));Aa.push("]");return Aa.join("")}function wa(La){for(var Ma=La.source.match(RegExp("(?:\\[(?:[^\\x5C\\x5D]|\\\\[\\s\\S])*\\]|\\\\u[A-Fa-f0-9]{4}|\\\\x[A-Fa-f0-9]{2}|\\\\[0-9]+|\\\\[^ux0-9]|\\(\\?[:!=]|[\\(\\)\\^]|[^\\x5B\\x5C\\(\\)\\^]+)","g")),Aa=Ma.length,za=[],Ja=0,jb=0;Ja<Aa;++Ja){var Xa=Ma[Ja];"("===Xa?++jb:"\\"===Xa.charAt(0)&&(Xa=+Xa.substring(1))&&Xa<=jb&&(za[Xa]=-1)}for(Ja=1;Ja<za.length;++Ja)-1===za[Ja]&&(za[Ja]=
++Ia);for(jb=Ja=0;Ja<Aa;++Ja)Xa=Ma[Ja],"("===Xa?(++jb,void 0===za[jb]&&(Ma[Ja]="(?:")):"\\"===Xa.charAt(0)&&(Xa=+Xa.substring(1))&&Xa<=jb&&(Ma[Ja]="\\"+za[jb]);for(jb=Ja=0;Ja<Aa;++Ja)"^"===Ma[Ja]&&"^"!==Ma[Ja+1]&&(Ma[Ja]="");if(La.ignoreCase&&Ka)for(Ja=0;Ja<Aa;++Ja)Xa=Ma[Ja],La=Xa.charAt(0),2<=Xa.length&&"["===La?Ma[Ja]=ka(Xa):"\\"!==La&&(Ma[Ja]=Xa.replace(/[a-zA-Z]/g,function(ub){ub=ub.charCodeAt(0);return"["+String.fromCharCode(ub&-33,ub|32)+"]"}));return Ma.join("")}for(var Ia=0,Ka=!1,la=!1,Ga=
0,Wa=ea.length;Ga<Wa;++Ga){var da=ea[Ga];if(da.ignoreCase)la=!0;else if(/[a-z]/i.test(da.source.replace(/\\u[0-9a-f]{4}|\\x[0-9a-f]{2}|\\[^ux]/gi,""))){Ka=!0;la=!1;break}}var ib=[];Ga=0;for(Wa=ea.length;Ga<Wa;++Ga){da=ea[Ga];if(da.global||da.multiline)throw Error(""+da);ib.push("(?:"+wa(da)+")")}return new RegExp(ib.join("|"),la?"gi":"g")}function d(ea){var X=0;return function(ma){for(var ka=null,wa=0,Ia=0,Ka=ma.length;Ia<Ka;++Ia)switch(ma.charAt(Ia)){case "\t":ka||(ka=[]);ka.push(ma.substring(wa,
Ia));wa=ea-X%ea;for(X+=wa;0<=wa;wa-=16)ka.push("                ".substring(0,wa));wa=Ia+1;break;case "\n":X=0;break;default:++X}if(!ka)return ma;ka.push(ma.substring(wa));return ka.join("")}}function e(ea,X,ma,ka){X&&(ea={source:X,Ck:ea},ma(ea),ka.push.apply(ka,ea.Sk))}function f(ea,X){function ma(Ka){for(var la=Ka.Ck,Ga=[la,"pln"],Wa=0,da=Ka.source.match(wa)||[],ib={},La=0,Ma=da.length;La<Ma;++La){var Aa=da[La],za=ib[Aa],Ja=void 0;if("string"===typeof za)var jb=!1;else{var Xa=ka[Aa.charAt(0)];if(Xa)Ja=
Aa.match(Xa[1]),za=Xa[0];else{for(jb=0;jb<Ia;++jb)if(Xa=X[jb],Ja=Aa.match(Xa[1])){za=Xa[0];break}Ja||(za="pln")}!(jb=5<=za.length&&"lang-"===za.substring(0,5))||Ja&&"string"===typeof Ja[1]||(jb=!1,za="src");jb||(ib[Aa]=za)}Xa=Wa;Wa+=Aa.length;if(jb){jb=Ja[1];var ub=Aa.indexOf(jb),ec=ub+jb.length;Ja[2]&&(ec=Aa.length-Ja[2].length,ub=ec-jb.length);za=za.substring(5);e(la+Xa,Aa.substring(0,ub),ma,Ga);e(la+Xa+ub,jb,m(za,jb),Ga);e(la+Xa+ec,Aa.substring(ec),ma,Ga)}else Ga.push(la+Xa,za)}Ka.Sk=Ga}var ka=
{},wa;(function(){for(var Ka=ea.concat(X),la=[],Ga={},Wa=0,da=Ka.length;Wa<da;++Wa){var ib=Ka[Wa],La=ib[3];if(La)for(var Ma=La.length;0<=--Ma;)ka[La.charAt(Ma)]=ib;ib=ib[1];La=""+ib;Ga.hasOwnProperty(La)||(la.push(ib),Ga[La]=null)}la.push(/[\0-\uffff]/);wa=c(la)})();var Ia=X.length;return ma}function h(ea){var X=[],ma=[];ea.tripleQuotedStrings?X.push(["str",/^(?:'''(?:[^'\\]|\\[\s\S]|'{1,2}(?=[^']))*(?:'''|$)|"""(?:[^"\\]|\\[\s\S]|"{1,2}(?=[^"]))*(?:"""|$)|'(?:[^\\']|\\[\s\S])*(?:'|$)|"(?:[^\\"]|\\[\s\S])*(?:"|$))/,
null,"'\""]):ea.multiLineStrings?X.push(["str",/^(?:'(?:[^\\']|\\[\s\S])*(?:'|$)|"(?:[^\\"]|\\[\s\S])*(?:"|$)|`(?:[^\\`]|\\[\s\S])*(?:`|$))/,null,"'\"`"]):X.push(["str",/^(?:'(?:[^\\'\r\n]|\\.)*(?:'|$)|"(?:[^\\"\r\n]|\\.)*(?:"|$))/,null,"\"'"]);ea.verbatimStrings&&ma.push(["str",/^@"(?:[^"]|"")*(?:"|$)/,null]);var ka=ea.hashComments;ka&&(ea.cStyleComments?(1<ka?X.push(["com",/^#(?:##(?:[^#]|#(?!##))*(?:###|$)|.*)/,null,"#"]):X.push(["com",/^#(?:(?:define|elif|else|endif|error|ifdef|include|ifndef|line|pragma|undef|warning)\b|[^\r\n]*)/,
null,"#"]),ma.push(["str",/^<(?:(?:(?:\.\.\/)*|\/?)(?:[\w-]+(?:\/[\w-]+)+)?[\w-]+\.h|[a-z]\w*)>/,null])):X.push(["com",/^#[^\r\n]*/,null,"#"]));ea.cStyleComments&&(ma.push(["com",/^\/\/[^\r\n]*/,null]),ma.push(["com",/^\/\*[\s\S]*?(?:\*\/|$)/,null]));ea.regexLiterals&&ma.push(["lang-regex",new RegExp("^"+r+"(/(?=[^/*])(?:[^/\\x5B\\x5C]|\\x5C[\\s\\S]|\\x5B(?:[^\\x5C\\x5D]|\\x5C[\\s\\S])*(?:\\x5D|$))+/)")]);ea=ea.keywords.replace(/^\s+|\s+$/g,"");ea.length&&ma.push(["kwd",new RegExp("^(?:"+ea.replace(/\s+/g,
"|")+")\\b"),null]);X.push(["pln",/^\s+/,null," \r\n\t\u00a0"]);ma.push(["lit",/^@[a-z_$][a-z_$@0-9]*/i,null],["typ",/^@?[A-Z]+[a-z][A-Za-z_$@0-9]*/,null],["pln",/^[a-z_$][a-z_$@0-9]*/i,null],["lit",RegExp("^(?:0x[a-f0-9]+|(?:\\d(?:_\\d+)*\\d*(?:\\.\\d*)?|\\.\\d\\+)(?:e[+\\-]?\\d+)?)[a-z]*","i"),null,"0123456789"],["pun",/^.[^\s\w\.$@'"`\/#]*/,null]);return f(X,ma)}function k(ea){function X(Ne){if(Ne>Ga){Wa&&Wa!==da&&(la.push("</span>"),Wa=null);!Wa&&da&&(Wa=da,la.push('<span class="',Wa,'">'));var rf=
a(Ma(ma.substring(Ga,Ne))).replace(Xa?za:Aa,"$1&#160;");Xa=jb.test(rf);la.push(rf.replace(Ja,qf));Ga=Ne}}var ma=ea.source,ka=ea.vq,wa=ea.Sk,Ia=ea.gm,Ka=ea.$m,la=[],Ga=0,Wa=null,da=null,ib=0,La=0,Ma=d(window.PR_TAB_WIDTH),Aa=/([\r\n ]) /g,za=/(^| ) /gm,Ja=/\r\n?|\n/g,jb=/[ \r\n]$/,Xa=!0,ub=window._pr_isIE6();Ka=ub?Ka&&"PRE"===Ka.tagName?6===ub?"&#160;\r\n":7===ub?"&#160;<br />\r":8===ub?"&#160;<br />":"&#160;\r":"&#160;<br />":"<br />";if(Ia){var ec=[];for(ub=0;10>ub;++ub)ec[ub]=Ka+'</li><li class="L'+
ub+'">';var Vd="number"===typeof Ia?Ia-1:0;la.push('<ol class="linenums"><li class="L',Vd%10,'"');Vd&&la.push(' value="',Vd+1,'"');la.push(">");var qf=function(){var Ne=ec[++Vd%10];return Wa?"</span>"+Ne+'<span class="'+Wa+'">':Ne}}else qf=Ka;for(;;)if(ib<ka.length&&(La<wa.length?ka[ib]<=wa[La]:1))X(ka[ib]),Wa&&(la.push("</span>"),Wa=null),la.push(ka[ib+1]),ib+=2;else if(La<wa.length)X(wa[La]),da=wa[La+1],La+=2;else break;X(ma.length);Wa&&la.push("</span>");Ia&&la.push("</li></ol>");ea.Mi=la.join("")}
function l(ea,X){for(var ma=X.length;0<=--ma;){var ka=X[ma];va.hasOwnProperty(ka)?"console"in window&&console.warn("cannot override language handler %s",ka):va[ka]=ea}}function m(ea,X){ea&&va.hasOwnProperty(ea)||(ea=/^\s*</.test(X)?"default-markup":"default-code");return va[ea]}function n(ea){var X=ea.Zm,ma=ea.Tl;ea.Mi=X;try{var ka=X.match(W);X=[];var wa=0,Ia=[];if(ka)for(var Ka=0,la=ka.length;Ka<la;++Ka){var Ga=ka[Ka];if(1<Ga.length&&"<"===Ga.charAt(0)){if(!Y.test(Ga))if(na.test(Ga))X.push(Ga.substring(9,
Ga.length-3)),wa+=Ga.length-12;else if(Fa.test(Ga))X.push("\n"),++wa;else if(0<=Ga.indexOf("nocode")&&Ga.replace(/\s(\w+)\s*=\s*(?:"([^"]*)"|'([^']*)'|(\S+))/g,' $1="$2$3$4"').match(/[cC][lL][aA][sS][sS]="[^"]*\bnocode\b/)){var Wa=Ga.match(ta)[2],da=1;var ib=Ka+1;a:for(;ib<la;++ib){var La=ka[ib].match(ta);if(La&&La[2]===Wa)if("/"===La[1]){if(0===--da)break a}else++da}ib<la?(Ia.push(wa,ka.slice(Ka,ib+1).join("")),Ka=ib):Ia.push(wa,Ga)}else Ia.push(wa,Ga)}else{da=Ga;var Ma=da.indexOf("&");if(0>Ma)var Aa=
da;else{for(--Ma;0<=(Ma=da.indexOf("&#",Ma+1));){var za=da.indexOf(";",Ma);if(0<=za){var Ja=da.substring(Ma+3,za),jb=10;Ja&&"x"===Ja.charAt(0)&&(Ja=Ja.substring(1),jb=16);var Xa=parseInt(Ja,jb);isNaN(Xa)||(da=da.substring(0,Ma)+String.fromCharCode(Xa)+da.substring(za+1))}}Aa=da.replace(y,"<").replace(x,">").replace(z,"'").replace(P,'"').replace(Q," ").replace(S,"&")}X.push(Aa);wa+=Aa.length}}var ub=X.join("");ea.source=ub;ea.Ck=0;ea.vq=Ia;m(ma,ub)(ea);k(ea)}catch(ec){"console"in window&&console.log(ec&&
ec.stack?ec.stack:ec)}}var r=function(){for(var ea="! != !== # % %= & && &&= &= ( * *= += , -= -> / /= : :: ; < << <<= <= = == === > >= >> >>= >>> >>>= ? @ [ ^ ^= ^^ ^^= { | |= || ||= ~ break case continue delete do else finally instanceof return throw try typeof".split(" "),X="(?:^^|[+-]",ma=0;ma<ea.length;++ma)X+="|"+ea[ma].replace(/([^=<>:&a-z])/g,"\\$1");return X+")\\s*"}(),t=/&/g,u=/</g,v=/>/g,w=/"/g,y=/&lt;/g,x=/&gt;/g,z=/&apos;/g,P=/&quot;/g,S=/&amp;/g,Q=/&nbsp;/g,ba=/[\r\n]/g,U=null,W=RegExp("[^<]+|\x3c!--[\\s\\S]*?--\x3e|<!\\[CDATA\\[[\\s\\S]*?\\]\\]>|</?[a-zA-Z](?:[^>\"']|'[^']*'|\"[^\"]*\")*>|<",
"g"),Y=/^\x3c!--/,na=/^<!\[CDATA\[/,Fa=/^<br\b/i,ta=/^<(\/?)([a-zA-Z][a-zA-Z0-9]*)/,ia=h({keywords:"break continue do else for if return while auto case char const default double enum extern float goto int long register short signed sizeof static struct switch typedef union unsigned void volatile catch class delete false import new operator private protected public this throw true try typeof alignof align_union asm axiom bool concept concept_map const_cast constexpr decltype dynamic_cast explicit export friend inline late_check mutable namespace nullptr reinterpret_cast static_assert static_cast template typeid typename using virtual wchar_t where break continue do else for if return while auto case char const default double enum extern float goto int long register short signed sizeof static struct switch typedef union unsigned void volatile catch class delete false import new operator private protected public this throw true try typeof abstract boolean byte extends final finally implements import instanceof null native package strictfp super synchronized throws transient as base by checked decimal delegate descending dynamic event fixed foreach from group implicit in interface internal into is lock object out override orderby params partial readonly ref sbyte sealed stackalloc string select uint ulong unchecked unsafe ushort var break continue do else for if return while auto case char const default double enum extern float goto int long register short signed sizeof static struct switch typedef union unsigned void volatile catch class delete false import new operator private protected public this throw true try typeof debugger eval export function get null set undefined var with Infinity NaN caller delete die do dump elsif eval exit foreach for goto if import last local my next no our print package redo require sub undef unless until use wantarray while BEGIN END break continue do else for if return while and as assert class def del elif except exec finally from global import in is lambda nonlocal not or pass print raise try with yield False True None break continue do else for if return while alias and begin case class def defined elsif end ensure false in module next nil not or redo rescue retry self super then true undef unless until when yield BEGIN END break continue do else for if return while case done elif esac eval fi function in local set then until ",
hashComments:!0,cStyleComments:!0,multiLineStrings:!0,regexLiterals:!0}),va={};l(ia,["default-code"]);l(f([],[["pln",/^[^<?]+/],["dec",/^<!\w[^>]*(?:>|$)/],["com",/^\x3c!--[\s\S]*?(?:-\->|$)/],["lang-",/^<\?([\s\S]+?)(?:\?>|$)/],["lang-",/^<%([\s\S]+?)(?:%>|$)/],["pun",/^(?:<[%?]|[%?]>)/],["lang-",/^<xmp\b[^>]*>([\s\S]+?)<\/xmp\b[^>]*>/i],["lang-js",/^<script\b[^>]*>([\s\S]*?)(<\/script\b[^>]*>)/i],["lang-css",/^<style\b[^>]*>([\s\S]*?)(<\/style\b[^>]*>)/i],["lang-in.tag",/^(<\/?[a-z][^<>]*>)/i]]),
"default-markup htm html mxml xhtml xml xsl".split(" "));l(f([["pln",/^[\s]+/,null," \t\r\n"],["atv",/^(?:"[^"]*"?|'[^']*'?)/,null,"\"'"]],[["tag",/^^<\/?[a-z](?:[\w.:-]*\w)?|\/?>$/i],["atn",/^(?!style[\s=]|on)[a-z](?:[\w:-]*\w)?/i],["lang-uq.val",/^=\s*([^>'"\s]*(?:[^>'"\s\/]|\/(?=\s)))/],["pun",/^[=<>\/]+/],["lang-js",/^on\w+\s*=\s*"([^"]+)"/i],["lang-js",/^on\w+\s*=\s*'([^']+)'/i],["lang-js",/^on\w+\s*=\s*([^"'>\s]+)/i],["lang-css",/^style\s*=\s*"([^"]+)"/i],["lang-css",/^style\s*=\s*'([^']+)'/i],
["lang-css",/^style\s*=\s*([^"'>\s]+)/i]]),["in.tag"]);l(f([],[["atv",/^[\s\S]+/]]),["uq.val"]);l(h({keywords:"break continue do else for if return while auto case char const default double enum extern float goto int long register short signed sizeof static struct switch typedef union unsigned void volatile catch class delete false import new operator private protected public this throw true try typeof alignof align_union asm axiom bool concept concept_map const_cast constexpr decltype dynamic_cast explicit export friend inline late_check mutable namespace nullptr reinterpret_cast static_assert static_cast template typeid typename using virtual wchar_t where ",
hashComments:!0,cStyleComments:!0}),"c cc cpp cxx cyc m".split(" "));l(h({keywords:"null true false"}),["json"]);l(h({keywords:"break continue do else for if return while auto case char const default double enum extern float goto int long register short signed sizeof static struct switch typedef union unsigned void volatile catch class delete false import new operator private protected public this throw true try typeof abstract boolean byte extends final finally implements import instanceof null native package strictfp super synchronized throws transient as base by checked decimal delegate descending dynamic event fixed foreach from group implicit in interface internal into is lock object out override orderby params partial readonly ref sbyte sealed stackalloc string select uint ulong unchecked unsafe ushort var ",
hashComments:!0,cStyleComments:!0,verbatimStrings:!0}),["cs"]);l(h({keywords:"break continue do else for if return while auto case char const default double enum extern float goto int long register short signed sizeof static struct switch typedef union unsigned void volatile catch class delete false import new operator private protected public this throw true try typeof abstract boolean byte extends final finally implements import instanceof null native package strictfp super synchronized throws transient ",
cStyleComments:!0}),["java"]);l(h({keywords:"break continue do else for if return while case done elif esac eval fi function in local set then until ",hashComments:!0,multiLineStrings:!0}),["bsh","csh","sh"]);l(h({keywords:"break continue do else for if return while and as assert class def del elif except exec finally from global import in is lambda nonlocal not or pass print raise try with yield False True None ",hashComments:!0,multiLineStrings:!0,tripleQuotedStrings:!0}),["cv","py"]);l(h({keywords:"caller delete die do dump elsif eval exit foreach for goto if import last local my next no our print package redo require sub undef unless until use wantarray while BEGIN END ",
hashComments:!0,multiLineStrings:!0,regexLiterals:!0}),["perl","pl","pm"]);l(h({keywords:"break continue do else for if return while alias and begin case class def defined elsif end ensure false in module next nil not or redo rescue retry self super then true undef unless until when yield BEGIN END ",hashComments:!0,multiLineStrings:!0,regexLiterals:!0}),["rb"]);l(h({keywords:"break continue do else for if return while auto case char const default double enum extern float goto int long register short signed sizeof static struct switch typedef union unsigned void volatile catch class delete false import new operator private protected public this throw true try typeof debugger eval export function get null set undefined var with Infinity NaN ",
cStyleComments:!0,regexLiterals:!0}),["js"]);l(h({keywords:"all and by catch class else extends false finally for if in is isnt loop new no not null of off on or return super then true try unless until when while yes ",hashComments:3,cStyleComments:!0,multilineStrings:!0,tripleQuotedStrings:!0,regexLiterals:!0}),["coffee"]);l(f([],[["str",/^[\s\S]+/]]),["regex"]);window.PR_normalizedHtml=b;window.prettyPrintOne=function(ea,X,ma){ea={Zm:ea,Tl:X,gm:ma};n(ea);return ea.Mi};window.prettyPrint=function(ea){function X(){for(var da=
window.PR_SHOULD_USE_CONTINUATION?la.now()+250:Infinity;Ga<ka.length&&la.now()<da;Ga++){var ib=ka[Ga];if(ib.className&&0<=ib.className.indexOf("prettyprint")){var La=ib.className.match(/\blang-(\w+)\b/);La&&(La=La[1]);for(var Ma=!1,Aa=ib.parentNode;Aa;Aa=Aa.parentNode)if(("pre"===Aa.tagName||"code"===Aa.tagName||"xmp"===Aa.tagName)&&Aa.className&&0<=Aa.className.indexOf("prettyprint")){Ma=!0;break}if(!Ma){Aa=ib;null===U&&(Ma=document.createElement("PRE"),Ma.appendChild(document.createTextNode('<!DOCTYPE foo PUBLIC "foo bar">\n<foo />')),
U=!/</.test(Ma.innerHTML));if(U)if(Ma=Aa.innerHTML,"XMP"===Aa.tagName)Ma=a(Ma);else{if("PRE"!==Aa.tagName&&ba.test(Ma)){var za="";Aa.currentStyle?za=Aa.currentStyle.whiteSpace:window.getComputedStyle&&(za=window.getComputedStyle(Aa,null).whiteSpace);Aa=!za||"pre"===za}else Aa=!0;Aa||(Ma=Ma.replace(/(<br\s*\/?>)[\r\n]+/g,"$1").replace(/(?:[\r\n]+[ \t]*)+/g," "))}else{Ma=[];for(Aa=Aa.firstChild;Aa;Aa=Aa.nextSibling)b(Aa,Ma);Ma=Ma.join("")}Ma=Ma.replace(/(?:\r\n?|\n)$/,"");Aa=ib.className.match(/\blinenums\b(?::(\d+))?/);
Wa={Zm:Ma,Tl:La,$m:ib,gm:Aa?Aa[1]&&Aa[1].length?+Aa[1]:!0:!1};n(Wa);if(ib=Wa.Mi)if(La=Wa.$m,"XMP"===La.tagName){Ma=document.createElement("PRE");for(Aa=0;Aa<La.attributes.length;++Aa)za=La.attributes[Aa],za.specified&&("class"===za.name.toLowerCase()?Ma.className=za.value:Ma.setAttribute(za.name,za.value));Ma.innerHTML=ib;La.parentNode.replaceChild(Ma,La)}else La.innerHTML=ib}}}Ga<ka.length?setTimeout(X,250):ea&&ea()}for(var ma=[document.getElementsByTagName("pre"),document.getElementsByTagName("code"),
document.getElementsByTagName("xmp")],ka=[],wa=0;wa<ma.length;++wa)for(var Ia=0,Ka=ma[wa].length;Ia<Ka;++Ia)ka.push(ma[wa][Ia]);ma=null;var la=Date;la.now||(la={now:function(){return(new Date).getTime()}});var Ga=0,Wa;X()};window.PR={combinePrefixPatterns:c,createSimpleLexer:f,registerLangHandler:l,sourceDecorator:h,PR_ATTRIB_NAME:"atn",PR_ATTRIB_VALUE:"atv",PR_COMMENT:"com",PR_DECLARATION:"dec",PR_KEYWORD:"kwd",PR_LITERAL:"lit",PR_NOCODE:"nocode",PR_PLAIN:"pln",PR_PUNCTUATION:"pun",PR_SOURCE:"src",
PR_STRING:"str",PR_TAG:"tag",PR_TYPE:"typ"}})();/*
 Copyright (C) 2009 Onno Hommes.

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

      http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
*/
PR.registerLangHandler(PR.createSimpleLexer([[PR.PR_COMMENT,/^#[^\r\n]*/,null,"#"],[PR.PR_PLAIN,/^[\t\n\r \xA0]+/,null,"\t\n\r \u00a0"],[PR.PR_STRING,/^"(?:[^"\\]|\\[\s\S])*(?:"|$)/,null,'"']],[[PR.PR_KEYWORD,/^(?:ADS|AD|AUG|BZF|BZMF|CAE|CAF|CA|CCS|COM|CS|DAS|DCA|DCOM|DCS|DDOUBL|DIM|DOUBLE|DTCB|DTCF|DV|DXCH|EDRUPT|EXTEND|INCR|INDEX|NDX|INHINT|LXCH|MASK|MSK|MP|MSU|NOOP|OVSK|QXCH|RAND|READ|RELINT|RESUME|RETURN|ROR|RXOR|SQUARE|SU|TCR|TCAA|OVSK|TCF|TC|TS|WAND|WOR|WRITE|XCH|XLQ|XXALQ|ZL|ZQ|ADD|ADZ|SUB|SUZ|MPY|MPR|MPZ|DVP|COM|ABS|CLA|CLZ|LDQ|STO|STQ|ALS|LLS|LRS|TRA|TSQ|TMI|TOV|AXT|TIX|DLY|INP|OUT)\s/,
null],[PR.PR_TYPE,/^(?:-?GENADR|=MINUS|2BCADR|VN|BOF|MM|-?2CADR|-?[1-6]DNADR|ADRES|BBCON|[SE]?BANK=?|BLOCK|BNKSUM|E?CADR|COUNT\*?|2?DEC\*?|-?DNCHAN|-?DNPTR|EQUALS|ERASE|MEMORY|2?OCT|REMADR|SETLOC|SUBRO|ORG|BSS|BES|SYN|EQU|DEFINE|END)\s/,null],[PR.PR_LITERAL,/^'(?:-*(?:\w|\\[\x21-\x7e])(?:[\w-]*|\\[\x21-\x7e])[=!?]?)?/],[PR.PR_PLAIN,/^-*(?:[!-z_]|\\[\x21-\x7e])(?:[\w-]*|\\[\x21-\x7e])[=!?]?/i],[PR.PR_PUNCTUATION,/^[^\w\t\n\r \xA0()"\\';]+/]]),["apollo","agc","aea"]);/*
 Copyright (C) 2011 Google Inc.

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

      http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
*/
PR.registerLangHandler(PR.createSimpleLexer([["opn",/^[\(\{\[]+/,null,"([{"],["clo",/^[\)\}\]]+/,null,")]}"],[PR.PR_COMMENT,/^;[^\r\n]*/,null,";"],[PR.PR_PLAIN,/^[\t\n\r \xA0]+/,null,"\t\n\r \u00a0"],[PR.PR_STRING,/^"(?:[^"\\]|\\[\s\S])*(?:"|$)/,null,'"']],[[PR.PR_KEYWORD,/^(?:def|if|do|let|quote|var|fn|loop|recur|throw|try|monitor-enter|monitor-exit|defmacro|defn|defn-|macroexpand|macroexpand-1|for|doseq|dosync|dotimes|and|or|when|not|assert|doto|proxy|defstruct|first|rest|cons|defprotocol|deftype|defrecord|reify|defmulti|defmethod|meta|with-meta|ns|in-ns|create-ns|import|intern|refer|alias|namespace|resolve|ref|deref|refset|new|set!|memfn|to-array|into-array|aset|gen-class|reduce|map|filter|find|nil?|empty?|hash-map|hash-set|vec|vector|seq|flatten|reverse|assoc|dissoc|list|list?|disj|get|union|difference|intersection|extend|extend-type|extend-protocol|prn)\b/,
null],[PR.PR_TYPE,/^:[0-9a-zA-Z\-]+/]]),["clj"]);/*
 Copyright (C) 2009 Google Inc.

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

      http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
*/
PR.registerLangHandler(PR.createSimpleLexer([[PR.PR_PLAIN,/^[ \t\r\n\f]+/,null," \t\r\n\f"]],[[PR.PR_STRING,/^"(?:[^\n\r\f\\"]|\\(?:\r\n?|\n|\f)|\\[\s\S])*"/,null],[PR.PR_STRING,/^'(?:[^\n\r\f\\']|\\(?:\r\n?|\n|\f)|\\[\s\S])*'/,null],["lang-css-str",/^url\(([^\)"']*)\)/i],[PR.PR_KEYWORD,/^(?:url|rgb|!important|@import|@page|@media|@charset|inherit)(?=[^\-\w]|$)/i,null],["lang-css-kw",/^(-?(?:[_a-z]|(?:\\[0-9a-f]+ ?))(?:[_a-z0-9\-]|\\(?:\\[0-9a-f]+ ?))*)\s*:/i],[PR.PR_COMMENT,/^\/\*[^*]*\*+(?:[^\/*][^*]*\*+)*\//],
[PR.PR_COMMENT,/^(?:\x3c!--|--\x3e)/],[PR.PR_LITERAL,/^(?:\d+|\d*\.\d+)(?:%|[a-z]+)?/i],[PR.PR_LITERAL,/^#(?:[0-9a-f]{3}){1,2}/i],[PR.PR_PLAIN,/^-?(?:[_a-z]|(?:\\[\da-f]+ ?))(?:[_a-z\d\-]|\\(?:\\[\da-f]+ ?))*/i],[PR.PR_PUNCTUATION,/^[^\s\w'"]+/]]),["css"]);PR.registerLangHandler(PR.createSimpleLexer([],[[PR.PR_KEYWORD,/^-?(?:[_a-z]|(?:\\[\da-f]+ ?))(?:[_a-z\d\-]|\\(?:\\[\da-f]+ ?))*/i]]),["css-kw"]);PR.registerLangHandler(PR.createSimpleLexer([],[[PR.PR_STRING,/^[^\)"']+/]]),["css-str"]);/*
 Copyright (C) 2010 Google Inc.

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

      http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
*/
PR.registerLangHandler(PR.createSimpleLexer([[PR.PR_PLAIN,/^[\t\n\r \xA0]+/,null,"\t\n\r \u00a0"],[PR.PR_PLAIN,/^(?:"(?:[^"\\]|\\[\s\S])*(?:"|$)|'(?:[^'\\]|\\[\s\S])+(?:'|$))/,null,"\"'"]],[[PR.PR_COMMENT,/^(?:\/\/[^\r\n]*|\/\*[\s\S]*?\*\/)/],[PR.PR_PLAIN,/^(?:[^\/"']|\/(?![\/\*]))+/i]]),["go"]);PR.registerLangHandler(PR.createSimpleLexer([[PR.PR_PLAIN,/^[\t\n\x0B\x0C\r ]+/,null,"\t\n\x0B\f\r "],[PR.PR_STRING,/^"(?:[^"\\\n\x0C\r]|\\[\s\S])*(?:"|$)/,null,'"'],[PR.PR_STRING,/^'(?:[^'\\\n\x0C\r]|\\[^&])'?/,null,"'"],[PR.PR_LITERAL,/^(?:0o[0-7]+|0x[\da-f]+|\d+(?:\.\d+)?(?:e[+\-]?\d+)?)/i,null,"0123456789"]],[[PR.PR_COMMENT,/^(?:(?:--+(?:[^\r\n\x0C]*)?)|(?:\{-(?:[^-]|-+[^-\}])*-\}))/],[PR.PR_KEYWORD,/^(?:case|class|data|default|deriving|do|else|if|import|in|infix|infixl|infixr|instance|let|module|newtype|of|then|type|where|_)(?=[^a-zA-Z0-9']|$)/,
null],[PR.PR_PLAIN,/^(?:[A-Z][\w']*\.)*[a-zA-Z][\w']*/],[PR.PR_PUNCTUATION,/^[^\t\n\x0B\x0C\r a-zA-Z0-9'"]+/]]),["hs"]);/*

 Copyright (C) 2017 Micha? B?czkowski

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
*/
PR.registerLangHandler(PR.createSimpleLexer([[PR.PR_PLAIN,/^[\t\n\r \xA0]+/,null,"\t\n\r \u00a0"],[PR.PR_PUNCTUATION,/^[.!%&()*+,\-;<=>?\[\\\]^{|}:]+/,null,".!%&()*+,-;<=>?[\\]^{|}:"]],[[PR.PR_KEYWORD,/^\b(package|public|protected|private|open|abstract|constructor|final|override|import|for|while|as|typealias|get|set|((data|enum|annotation|sealed) )?class|this|super|val|var|fun|is|in|throw|return|break|continue|(companion )?object|if|try|else|do|when|init|interface|typeof|suspend)\b/],[PR.PR_LITERAL,
/^(?:true|false|null)\b/],[PR.PR_LITERAL,/^(0[xX][0-9a-fA-F_]+L?|0[bB][0-1]+L?|[0-9_.]+([eE]-?[0-9]+)?[fFL]?)/],[PR.PR_TYPE,/^(\b[A-Z]+[a-z][a-zA-Z0-9_$@]*|`.*`)/,null],[PR.PR_COMMENT,/^\/\/.*/],[PR.PR_COMMENT,/^\/\*[\s\S]*?(?:\*\/|$)/],[PR.PR_STRING,/'.'/],[PR.PR_STRING,/^"([^"\\]|\\[\s\S])*"/],[PR.PR_STRING,/^"{3}[\s\S]*?[^\\]"{3}/],[PR.PR_LITERAL,/^@([a-zA-Z0-9_$@]*|`.*`)/],[PR.PR_LITERAL,/^[a-zA-Z0-9_]+@/]]),["kotlin"]);/*
 Copyright (C) 2008 Google Inc.

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

      http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
*/
PR.registerLangHandler(PR.createSimpleLexer([["opn",/^\(+/,null,"("],["clo",/^\)+/,null,")"],[PR.PR_COMMENT,/^;[^\r\n]*/,null,";"],[PR.PR_PLAIN,/^[\t\n\r \xA0]+/,null,"\t\n\r \u00a0"],[PR.PR_STRING,/^"(?:[^"\\]|\\[\s\S])*(?:"|$)/,null,'"']],[[PR.PR_KEYWORD,/^(?:block|c[ad]+r|catch|con[ds]|def(?:ine|un)|do|eq|eql|equal|equalp|eval-when|flet|format|go|if|labels|lambda|let|load-time-value|locally|macrolet|multiple-value-call|nil|progn|progv|quote|require|return-from|setq|symbol-macrolet|t|tagbody|the|throw|unwind)\b/,
null],[PR.PR_LITERAL,/^[+\-]?(?:[0#]x[0-9a-f]+|\d+\/\d+|(?:\.\d+|\d+(?:\.\d*)?)(?:[ed][+\-]?\d+)?)/i],[PR.PR_LITERAL,/^'(?:-*(?:\w|\\[\x21-\x7e])(?:[\w-]*|\\[\x21-\x7e])[=!?]?)?/],[PR.PR_PLAIN,/^-*(?:[a-z_]|\\[\x21-\x7e])(?:[\w-]*|\\[\x21-\x7e])[=!?]?/i],[PR.PR_PUNCTUATION,/^[^\w\t\n\r \xA0()"\\';]+/]]),["cl","el","lisp","scm"]);PR.registerLangHandler(PR.createSimpleLexer([[PR.PR_PLAIN,/^[\t\n\r \xA0]+/,null,"\t\n\r \u00a0"],[PR.PR_STRING,/^(?:"(?:[^"\\]|\\[\s\S])*(?:"|$)|'(?:[^'\\]|\\[\s\S])*(?:'|$))/,null,"\"'"]],[[PR.PR_COMMENT,/^--(?:\[(=*)\[[\s\S]*?(?:\]\1\]|$)|[^\r\n]*)/],[PR.PR_STRING,/^\[(=*)\[[\s\S]*?(?:\]\1\]|$)/],[PR.PR_KEYWORD,/^(?:and|break|do|else|elseif|end|false|for|function|if|in|local|nil|not|or|repeat|return|then|true|until|while)\b/,null],[PR.PR_LITERAL,/^[+-]?(?:0x[\da-f]+|(?:(?:\.\d+|\d+(?:\.\d*)?)(?:e[+\-]?\d+)?))/i],
[PR.PR_PLAIN,/^[a-z_]\w*/i],[PR.PR_PUNCTUATION,/^[^\w\t\n\r \xA0][^\w\t\n\r \xA0"'\-\+=]*/]]),["lua"]);PR.registerLangHandler(PR.createSimpleLexer([[PR.PR_PLAIN,/^[\t\n\r \xA0]+/,null,"\t\n\r \u00a0"],[PR.PR_COMMENT,/^#(?:if[\t\n\r \xA0]+(?:[a-z_$][\w']*|``[^\r\n\t`]*(?:``|$))|else|endif|light)/i,null,"#"],[PR.PR_STRING,/^(?:"(?:[^"\\]|\\[\s\S])*(?:"|$)|'(?:[^'\\]|\\[\s\S])(?:'|$))/,null,"\"'"]],[[PR.PR_COMMENT,/^(?:\/\/[^\r\n]*|\(\*[\s\S]*?\*\))/],[PR.PR_KEYWORD,/^(?:abstract|and|as|assert|begin|class|default|delegate|do|done|downcast|downto|elif|else|end|exception|extern|false|finally|for|fun|function|if|in|inherit|inline|interface|internal|lazy|let|match|member|module|mutable|namespace|new|null|of|open|or|override|private|public|rec|return|static|struct|then|to|true|try|type|upcast|use|val|void|when|while|with|yield|asr|land|lor|lsl|lsr|lxor|mod|sig|atomic|break|checked|component|const|constraint|constructor|continue|eager|event|external|fixed|functor|global|include|method|mixin|object|parallel|process|protected|pure|sealed|trait|virtual|volatile)\b/],
[PR.PR_LITERAL,/^[+\-]?(?:0x[\da-f]+|(?:(?:\.\d+|\d+(?:\.\d*)?)(?:e[+\-]?\d+)?))/i],[PR.PR_PLAIN,/^(?:[a-z_][\w']*[!?#]?|``[^\r\n\t`]*(?:``|$))/i],[PR.PR_PUNCTUATION,/^[^\t\n\r \xA0"'\w]+/]]),["fs","ml"]);PR.registerLangHandler(PR.sourceDecorator({keywords:"bool bytes default double enum extend extensions false fixed32 fixed64 float group import int32 int64 max message option optional package repeated required returns rpc service sfixed32 sfixed64 sint32 sint64 string syntax to true uint32 uint64",cStyleComments:!0}),["proto"]);PR.registerLangHandler(PR.createSimpleLexer([[PR.PR_PLAIN,/^[\t\n\r \xA0]+/,null,"\t\n\r \u00a0"],[PR.PR_STRING,/^(?:"(?:(?:""(?:""?(?!")|[^\\"]|\\.)*"{0,3})|(?:[^"\r\n\\]|\\.)*"?))/,null,'"'],[PR.PR_LITERAL,/^`(?:[^\r\n\\`]|\\.)*`?/,null,"`"],[PR.PR_PUNCTUATION,/^[!#%&()*+,\-:;<=>?@\[\\\]^{|}~]+/,null,"!#%&()*+,-:;<=>?@[\\]^{|}~"]],[[PR.PR_STRING,/^'(?:[^\r\n\\']|\\(?:'|[^\r\n']+))'/],[PR.PR_LITERAL,/^'[a-zA-Z_$][\w$]*(?!['$\w])/],[PR.PR_KEYWORD,/^(?:abstract|case|catch|class|def|do|else|extends|final|finally|for|forSome|if|implicit|import|lazy|match|new|object|override|package|private|protected|requires|return|sealed|super|throw|trait|try|type|val|var|while|with|yield)\b/],
[PR.PR_LITERAL,/^(?:true|false|null|this)\b/],[PR.PR_LITERAL,/^(?:(?:0(?:[0-7]+|X[0-9A-F]+))L?|(?:(?:0|[1-9][0-9]*)(?:(?:\.[0-9]+)?(?:E[+\-]?[0-9]+)?F?|L?))|\\.[0-9]+(?:E[+\-]?[0-9]+)?F?)/i],[PR.PR_TYPE,/^[$_]*[A-Z][_$A-Z0-9]*[a-z][\w$]*/],[PR.PR_PLAIN,/^[$a-zA-Z_][\w$]*/],[PR.PR_COMMENT,/^\/(?:\/.*|\*(?:\/|\**[^*/])*(?:\*+\/?)?)/],[PR.PR_PUNCTUATION,/^(?:\.+|\/)/]]),["scala"]);PR.registerLangHandler(PR.createSimpleLexer([[PR.PR_PLAIN,/^[\t\n\r \xA0]+/,null,"\t\n\r \u00a0"],[PR.PR_STRING,/^(?:"(?:[^"\\]|\\.)*"|'(?:[^'\\]|\\.)*')/,null,"\"'"]],[[PR.PR_COMMENT,/^(?:--[^\r\n]*|\/\*[\s\S]*?(?:\*\/|$))/],[PR.PR_KEYWORD,/^(?:ADD|ALL|ALTER|AND|ANY|AS|ASC|AUTHORIZATION|BACKUP|BEGIN|BETWEEN|BREAK|BROWSE|BULK|BY|CASCADE|CASE|CHECK|CHECKPOINT|CLOSE|CLUSTERED|COALESCE|COLLATE|COLUMN|COMMIT|COMPUTE|CONSTRAINT|CONTAINS|CONTAINSTABLE|CONTINUE|CONVERT|CREATE|CROSS|CURRENT|CURRENT_DATE|CURRENT_TIME|CURRENT_TIMESTAMP|CURRENT_USER|CURSOR|DATABASE|DBCC|DEALLOCATE|DECLARE|DEFAULT|DELETE|DENY|DESC|DISK|DISTINCT|DISTRIBUTED|DOUBLE|DROP|DUMMY|DUMP|ELSE|END|ERRLVL|ESCAPE|EXCEPT|EXEC|EXECUTE|EXISTS|EXIT|FETCH|FILE|FILLFACTOR|FOR|FOREIGN|FREETEXT|FREETEXTTABLE|FROM|FULL|FUNCTION|GOTO|GRANT|GROUP|HAVING|HOLDLOCK|IDENTITY|IDENTITYCOL|IDENTITY_INSERT|IF|IN|INDEX|INNER|INSERT|INTERSECT|INTO|IS|JOIN|KEY|KILL|LEFT|LIKE|LINENO|LOAD|NATIONAL|NOCHECK|NONCLUSTERED|NOT|NULL|NULLIF|OF|OFF|OFFSETS|ON|OPEN|OPENDATASOURCE|OPENQUERY|OPENROWSET|OPENXML|OPTION|OR|ORDER|OUTER|OVER|PERCENT|PLAN|PRECISION|PRIMARY|PRINT|PROC|PROCEDURE|PUBLIC|RAISERROR|READ|READTEXT|RECONFIGURE|REFERENCES|REPLICATION|RESTORE|RESTRICT|RETURN|REVOKE|RIGHT|ROLLBACK|ROWCOUNT|ROWGUIDCOL|RULE|SAVE|SCHEMA|SELECT|SESSION_USER|SET|SETUSER|SHUTDOWN|SOME|STATISTICS|SYSTEM_USER|TABLE|TEXTSIZE|THEN|TO|TOP|TRAN|TRANSACTION|TRIGGER|TRUNCATE|TSEQUAL|UNION|UNIQUE|UPDATE|UPDATETEXT|USE|USER|VALUES|VARYING|VIEW|WAITFOR|WHEN|WHERE|WHILE|WITH|WRITETEXT)(?=[^\w-]|$)/i,
null],[PR.PR_LITERAL,/^[+-]?(?:0x[\da-f]+|(?:(?:\.\d+|\d+(?:\.\d*)?)(?:e[+\-]?\d+)?))/i],[PR.PR_PLAIN,/^[a-z_][\w-]*/i],[PR.PR_PUNCTUATION,/^[^\w\t\n\r \xA0"'][^\w\t\n\r \xA0+\-"']*/]]),["sql"]);/*
 Copyright (C) 2015 Google Inc.
 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

      http://www.apache.org/licenses/LICENSE-2.0
 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
*/
PR.registerLangHandler(PR.createSimpleLexer([[PR.PR_PLAIN,/^[ \n\r\t\v\f\0]+/,null," \n\r\t\v\f\x00"],[PR.PR_STRING,/^"(?:[^"\\]|(?:\\.)|(?:\\\((?:[^"\\)]|\\.)*\)))*"/,null,'"']],[[PR.PR_LITERAL,/^(?:(?:0x[\da-fA-F][\da-fA-F_]*\.[\da-fA-F][\da-fA-F_]*[pP]?)|(?:\d[\d_]*\.\d[\d_]*[eE]?))[+-]?\d[\d_]*/,null],[PR.PR_LITERAL,/^-?(?:(?:0(?:(?:b[01][01_]*)|(?:o[0-7][0-7_]*)|(?:x[\da-fA-F][\da-fA-F_]*)))|(?:\d[\d_]*))/,null],[PR.PR_LITERAL,/^(?:true|false|nil)\b/,null],[PR.PR_KEYWORD,/^\b(?:__COLUMN__|__FILE__|__FUNCTION__|__LINE__|associativity|as|break|case|class|continue|convenience|default|deinit|didSet|do|dynamic|dynamicType|else|enum|fallthrough|final|for|func|get|import|infix|init|inout|internal|if|in|is|lazy|left|let|mutating|none|nonmutating|operator|optional|override|postfix|precedence|prefix|private|protocol|Protocol|public|required|return|right|safe|self|set|static|struct|subscript|super|switch|Type|typealias|unowned|unsafe|var|weak|while|willSet)\b/,
null],[PR.PR_COMMENT,/^\/\/.*?[\n\r]/,null],[PR.PR_COMMENT,/^\/\*[\s\S]*?(?:\*\/|$)/,null],[PR.PR_PUNCTUATION,/^<<=|<=|<<|>>=|>=|>>|===|==|\.\.\.|&&=|\.\.<|!==|!=|&=|~=|~|\(|\)|\[|\]|{|}|@|#|;|\.|,|:|\|\|=|\?\?|\|\||&&|&\*|&\+|&-|&=|\+=|-=|\/=|\*=|\^=|%=|\|=|->|`|==|\+\+|--|\/|\+|!|\*|%|<|>|&|\||\^|\?|=|-|_/,null],[PR.PR_TYPE,/^\b(?:[@_]?[A-Z]+[a-z][A-Za-z_$@0-9]*|\w+_t\b)/,null]]),["swift"]);PR.registerLangHandler(PR.createSimpleLexer([[PR.PR_PLAIN,/^[\t\n\r \xA0\u2028\u2029]+/,null,"\t\n\r \u00a0\u2028\u2029"],[PR.PR_STRING,/^(?:["\u201C\u201D](?:[^"\u201C\u201D]|["\u201C\u201D]{2})(?:["\u201C\u201D]c|$)|["\u201C\u201D](?:[^"\u201C\u201D]|["\u201C\u201D]{2})*(?:["\u201C\u201D]|$))/i,null,'"\u201c\u201d'],[PR.PR_COMMENT,/^['\u2018\u2019][^\r\n\u2028\u2029]*/,null,"'\u2018\u2019"]],[[PR.PR_KEYWORD,/^(?:AddHandler|AddressOf|Alias|And|AndAlso|Ansi|As|Assembly|Auto|Boolean|ByRef|Byte|ByVal|Call|Case|Catch|CBool|CByte|CChar|CDate|CDbl|CDec|Char|CInt|Class|CLng|CObj|Const|CShort|CSng|CStr|CType|Date|Decimal|Declare|Default|Delegate|Dim|DirectCast|Do|Double|Each|Else|ElseIf|End|EndIf|Enum|Erase|Error|Event|Exit|Finally|For|Friend|Function|Get|GetType|GoSub|GoTo|Handles|If|Implements|Imports|In|Inherits|Integer|Interface|Is|Let|Lib|Like|Long|Loop|Me|Mod|Module|MustInherit|MustOverride|MyBase|MyClass|Namespace|New|Next|Not|NotInheritable|NotOverridable|Object|On|Option|Optional|Or|OrElse|Overloads|Overridable|Overrides|ParamArray|Preserve|Private|Property|Protected|Public|RaiseEvent|ReadOnly|ReDim|RemoveHandler|Resume|Return|Select|Set|Shadows|Shared|Short|Single|Static|Step|Stop|String|Structure|Sub|SyncLock|Then|Throw|To|Try|TypeOf|Unicode|Until|Variant|Wend|When|While|With|WithEvents|WriteOnly|Xor|EndIf|GoSub|Let|Variant|Wend)\b/i,
null],[PR.PR_COMMENT,/^REM[^\r\n\u2028\u2029]*/i],[PR.PR_LITERAL,/^(?:True\b|False\b|Nothing\b|\d+(?:E[+\-]?\d+[FRD]?|[FRDSIL])?|(?:&H[0-9A-F]+|&O[0-7]+)[SIL]?|\d*\.\d+(?:E[+\-]?\d+)?[FRD]?|#\s+(?:\d+[\-\/]\d+[\-\/]\d+(?:\s+\d+:\d+(?::\d+)?(\s*(?:AM|PM))?)?|\d+:\d+(?::\d+)?(\s*(?:AM|PM))?)\s+#)/i],[PR.PR_PLAIN,/^(?:(?:[a-z]|_\w)\w*|\[(?:[a-z]|_\w)\w*\])/i],[PR.PR_PUNCTUATION,/^[^\w\t\n\r "'\[\]\xA0\u2018\u2019\u201C\u201D\u2028\u2029]+/],[PR.PR_PUNCTUATION,/^(?:\[|\])/]]),["vb","vbs"]);PR.registerLangHandler(PR.createSimpleLexer([[PR.PR_PLAIN,/^[\t\n\r \xA0]+/,null,"\t\n\r \u00a0"]],[[PR.PR_STRING,/^(?:[BOX]?"(?:[^"]|"")*"|'.')/i],[PR.PR_COMMENT,/^--[^\r\n]*/],[PR.PR_KEYWORD,/^(?:abs|access|after|alias|all|and|architecture|array|assert|attribute|begin|block|body|buffer|bus|case|component|configuration|constant|disconnect|downto|else|elsif|end|entity|exit|file|for|function|generate|generic|group|guarded|if|impure|in|inertial|inout|is|label|library|linkage|literal|loop|map|mod|nand|new|next|nor|not|null|of|on|open|or|others|out|package|port|postponed|procedure|process|pure|range|record|register|reject|rem|report|return|rol|ror|select|severity|shared|signal|sla|sll|sra|srl|subtype|then|to|transport|type|unaffected|units|until|use|variable|wait|when|while|with|xnor|xor)(?=[^\w-]|$)/i,
null],[PR.PR_TYPE,/^(?:bit|bit_vector|character|boolean|integer|real|time|string|severity_level|positive|natural|signed|unsigned|line|text|std_u?logic(?:_vector)?)(?=[^\w-]|$)/i,null],[PR.PR_TYPE,/^'(?:ACTIVE|ASCENDING|BASE|DELAYED|DRIVING|DRIVING_VALUE|EVENT|HIGH|IMAGE|INSTANCE_NAME|LAST_ACTIVE|LAST_EVENT|LAST_VALUE|LEFT|LEFTOF|LENGTH|LOW|PATH_NAME|POS|PRED|QUIET|RANGE|REVERSE_RANGE|RIGHT|RIGHTOF|SIMPLE_NAME|STABLE|SUCC|TRANSACTION|VAL|VALUE)(?=[^\w-]|$)/i,null],[PR.PR_LITERAL,/^\d+(?:_\d+)*(?:#[\w\\.]+#(?:[+\-]?\d+(?:_\d+)*)?|(?:\.\d+(?:_\d+)*)?(?:E[+\-]?\d+(?:_\d+)*)?)/i],
[PR.PR_PLAIN,/^(?:[a-z]\w*|\\[^\\]*\\)/i],[PR.PR_PUNCTUATION,/^[^\w\t\n\r \xA0"'][^\w\t\n\r \xA0\-"']*/]]),["vhdl","vhd"]);PR.registerLangHandler(PR.createSimpleLexer([[PR.PR_PLAIN,/^[\t \xA0a-gi-z0-9]+/,null,"\t \u00a0abcdefgijklmnopqrstuvwxyz0123456789"],[PR.PR_PUNCTUATION,/^[=*~\^\[\]]+/,null,"=*~^[]"]],[["lang-wiki.meta",/(?:^^|\r\n?|\n)(#[a-z]+)\b/],[PR.PR_LITERAL,/^(?:[A-Z][a-z][a-z0-9]+[A-Z][a-z][a-zA-Z0-9]+)\b/],["lang-",/^\{\{\{([\s\S]+?)\}\}\}/],["lang-",/^`([^\r\n`]+)`/],[PR.PR_STRING,/^https?:\/\/[^\/?#\s]*(?:\/[^?#\s]*)?(?:\?[^#\s]*)?(?:#\S*)?/i],[PR.PR_PLAIN,/^(?:\r\n|[\s\S])[^#=*~^A-Zh\{`\[\r\n]*/]]),["wiki"]);
PR.registerLangHandler(PR.createSimpleLexer([[PR.PR_KEYWORD,/^#[a-z]+/i,null,"#"]],[]),["wiki.meta"]);PR.registerLangHandler(PR.createSimpleLexer([[PR.PR_PUNCTUATION,/^[:|>?]+/,null,":|>?"],[PR.PR_DECLARATION,/^%(?:YAML|TAG)[^#\r\n]+/,null,"%"],[PR.PR_TYPE,/^[&]\S+/,null,"&"],[PR.PR_TYPE,/^!\S*/,null,"!"],[PR.PR_STRING,/^"(?:[^\\"]|\\.)*(?:"|$)/,null,'"'],[PR.PR_STRING,/^'(?:[^']|'')*(?:'|$)/,null,"'"],[PR.PR_COMMENT,/^#[^\r\n]*/,null,"#"],[PR.PR_PLAIN,/^\s+/,null," \t\r\n"]],[[PR.PR_DECLARATION,/^(?:---|\.\.\.)(?:[\r\n]|$)/],[PR.PR_PUNCTUATION,/^-/],[PR.PR_KEYWORD,/^\w+:[ \r\n]/],[PR.PR_PLAIN,/^\w+/]]),
["yaml","yml"]);_ds.q(LT,_ds.ci);LT.prototype.whenReady=function(){return this.M.promise};
LT.prototype.connectedCallback=function(){var a=this,b;return _ds.Va(function(c){switch(c.j){case 1:return _ds.A(c,DevsiteApp.whenReady(),2);case 2:return a.L||(NT(a),MT(a),a.L=!0),a.J.get("pref_dark-code")&&a.setAttribute("dark-code",""),a.M.resolve(),_ds.C(c,3),_ds.A(c,DevsiteApp.intersectionEnterForElement(a),5);case 5:_ds.D(c,4);break;case 3:if(b=_ds.E(c),"IntersectionObserver not supported"!==b.message)return c.return();case 4:var d=a.querySelector(".devsite-code-buttons-container");if(d)a.h=
d;else{a.h=_ds.xl(GT);a.hasAttribute("scope")&&(a.C=_ds.xl(KT,{label:"\u041e\u0442\u043a\u0440\u044b\u0442\u044c \u043f\u0440\u0438\u043c\u0435\u0440 \u043a\u043e\u0434\u0430 \u0432 JSFiddle"}),(a.hasAttribute("jsfiddle-label")||a.hasAttribute("jsfiddle-title"))&&a.C.setAttribute("data-label",a.getAttribute("jsfiddle-label")||a.getAttribute("jsfiddle-title")),a.h.appendChild(a.C));a.D=_ds.xl(HT,{label:"\u0422\u0451\u043c\u043d\u0430\u044f \u0442\u0435\u043c\u0430"});a.h.appendChild(a.D);a.F=_ds.xl(IT,
{label:"\u0421\u0432\u0435\u0442\u043b\u0430\u044f \u0442\u0435\u043c\u0430"});a.h.appendChild(a.F);if(!a.hasAttribute("no-copy")){d=a.getAttribute("data-copy-event-label");var e="Click To Copy";d&&(e+=": "+d);a.o=_ds.xl(JT,{label:a.K,Tp:e});a.h.appendChild(a.o)}a.prepend(a.h)}PT(a);a.H=document.querySelector("devsite-snackbar");_ds.B(c)}})};
LT.prototype.disconnectedCallback=function(){var a=this;return _ds.Va(function(b){if(1==b.j)return _ds.A(b,DevsiteApp.whenReady(),2);DevsiteApp.unregisterIntersectionForElement(a);a.h&&a.removeChild(a.h);_ds.Ol(a.m);_ds.B(b)})};
LT.prototype.attributeChangedCallback=function(a,b,c){var d=this;return _ds.Va(function(e){if(1==e.j){if("dark-code"!==a||b===c)return e.G(0);if(d.hasAttribute("dark-code"))return d.J.set("pref_dark-code","1"),_ds.A(e,_ds.Fm(),6);d.J.remove("pref_dark-code");return _ds.A(e,_ds.Fm(),5)}if(6!=e.j)return Array.from(document.querySelectorAll("devsite-code[dark-code]")).forEach(function(f){f.removeAttribute("dark-code")}),e.G(0);Array.from(document.querySelectorAll("devsite-code:not([dark-code])")).filter(function(f){return f!==
d}).forEach(function(f){f.setAttribute("dark-code","")});_ds.B(e)})};_ds.ja.Object.defineProperties(LT,{observedAttributes:{configurable:!0,enumerable:!0,get:function(){return["dark-code"]}}});LT.prototype.attributeChangedCallback=LT.prototype.attributeChangedCallback;LT.prototype.disconnectedCallback=LT.prototype.disconnectedCallback;LT.prototype.connectedCallback=LT.prototype.connectedCallback;LT.prototype.whenReady=LT.prototype.whenReady;try{window.customElements.define("devsite-code",LT)}catch(a){console.warn("devsite.app.customElement.DevsiteCode",a)};})(_ds_www);
