(function(_ds){var window=this;'use strict';var Z4=function(a,b){return _ds.aa[a]=b},$4=function(a){var b=arguments.length;if(1==b&&Array.isArray(arguments[0]))return $4.apply(null,arguments[0]);for(var c={},d=0;d<b;d++)c[arguments[d]]=!0;return c},a5=function(a,b,c,d,e,f,h,k,l,m){this.h=a;this.C=b;this.H=c;this.m=d;this.o=e;this.D=f;this.F=h;this.O=k;this.j=l;this.J=m},b5=function(a){return new a5(a.m,a.o,a.O,a.h,a.j,a.C,a.J,a.F,a.D,a.H)},c5=function(a,b){a.H=b;return a},d5=function(a,b){a.D=b;return a},e5=function(a,b){a.F=b;
return a},f5=function(){this.m=null;this.o="";this.H=this.D=this.F=this.J=this.C=this.j=this.h=this.O=null},g5=function(a){var b=a.oa;b=(b=b&&"composed"in b&&b&&"composedPath"in b&&b.composed&&b.composedPath())&&0<b.length?b[0]:a.target;return b5(c5(d5(e5((new f5).keyCode(a.keyCode||0).key(a.key||"").shiftKey(!!a.shiftKey).altKey(!!a.altKey).ctrlKey(!!a.ctrlKey).metaKey(!!a.metaKey).target(a.target),b),function(){return a.preventDefault()}),function(){return a.stopPropagation()}))},h5=function(a,
b,c){_ds.ch.call(this,a,c);this.j=b},i5=function(a){this.h=a||null;this.next=a?null:{}},j5=function(a,b){b.shift().forEach(function(c){var d=a[c];d&&(0==b.length?d.h&&delete a[c]:d.next&&(j5(d.next,b.slice(0)),_ds.Wb(d.next)&&delete a[c]))})},m5=function(a){a=a.replace(/[ +]*\+[ +]*/g,"+").replace(/[ ]+/g," ").toLowerCase();a=a.split(" ");for(var b=[],c,d=0;c=a[d];d++){var e=c.split("+"),f=null,h=null;c=0;for(var k,l=0;k=e[l];l++){switch(k){case "shift":c|=1;continue;case "ctrl":c|=2;continue;case "alt":c|=
4;continue;case "meta":c|=8;continue}e=void 0;f=k;if(!k5){h={};for(e in l5)h[l5[e]]=_ds.CE(parseInt(e,10));k5=h}h=k5[f];f=k;break}b.push({key:f,keyCode:h,modifiers:c})}return b},n5=function(a,b,c){c=c||0;b=["c_"+b+"_"+c];""!=a&&b.push("n_"+a+"_"+c);return b},o5=function(a,b){if("string"===typeof b[a])a=m5(b[a]).map(function(e){return n5(e.key||"",e.keyCode,e.modifiers)});else{var c=b,d=a;Array.isArray(b[a])&&(c=b[a],d=0);for(a=[];d<c.length;d+=2)a.push(n5("",c[d],c[d+1]))}return a},p5=function(a,
b){32==a.D&&32==b.h&&(0,b.j)();a.D=null},q5=function(a){return _ds.QK&&a.o&&a.m},r5=function(a,b,c){var d=b.shift();d.forEach(function(e){if((e=a[e])&&(0==b.length||e.h))throw Error("Keyboard shortcut conflicts with existing shortcut: "+e.h);});b.length?d.forEach(function(e){e=e.toString();var f=new i5;e=e in a?a[e]:a[e]=f;r5(e.next,b.slice(0),c)}):d.forEach(function(e){a[e]=new i5(c)})},s5=function(a,b){for(var c=0;c<b.length;c++){var d=a[b[c]];if(d)return d}},t5=function(a,b,c){a:{var d=b.h;if(""!=
b.C){var e=b.C;if("Control"==e||"Shift"==e||"Meta"==e||"AltGraph"==e){d=!1;break a}}else if(16==d||17==d||18==d){d=!1;break a}e=b.O;var f="TEXTAREA"==e.tagName||"INPUT"==e.tagName||"BUTTON"==e.tagName||"SELECT"==e.tagName,h=!f&&(e.isContentEditable||e.ownerDocument&&"on"==e.ownerDocument.designMode);d=!f&&!h||a.K[d]||a.F?!0:h?!1:a.L&&(b.m||b.o||b.D)?!0:"INPUT"==e.tagName&&a.T[e.type]?13==d:"INPUT"==e.tagName||"BUTTON"==e.tagName?a.M?!0:32!=d:!1}if(d)if(!c&&q5(b))a.o=!1;else{c=_ds.CE(b.h);d=n5(b.C,
c,(b.H?1:0)|(b.o?2:0)|(b.m?4:0)|(b.D?8:0));e=s5(a.m,d);if(!e||1500<=Date.now()-a.C)a.m=a.j,a.C=Date.now();(e=s5(a.m,d))&&e.next&&(a.m=e.next,a.C=Date.now());e&&(e.next?(0,b.j)():(a.m=a.j,a.C=Date.now(),a.H&&(0,b.j)(),a.J&&(0,b.J)(),d=e.h,e=a.dispatchEvent(new h5("shortcut",d,b.F)),(e&=a.dispatchEvent(new h5("shortcut_"+d,d,b.F)))||(0,b.j)(),_ds.Tn&&(a.D=c)))}},u5=function(a,b,c){for(;0<c.length&&b;){var d=c.shift();if((d=s5(b,d))&&(0==c.length&&d.h||u5(a,d.next,c.slice(0))))return!0}return!1},x5=
function(a){_ds.Vm.call(this);this.m=this.j={};this.C=0;this.K=$4(v5);this.T=$4(w5);this.H=!0;this.F=this.J=!1;this.L=!0;this.M=!1;this.D=null;this.h=a;_ds.qh(this.h,"keydown",this.xl,void 0,this);_ds.qh(this.h,"synthetic-keydown",this.El,void 0,this);_ds.QK&&(_ds.qh(this.h,"keypress",this.Gl,void 0,this),_ds.qh(this.h,"synthetic-keypress",this.Hl,void 0,this));_ds.qh(this.h,"keyup",this.yl,void 0,this);_ds.qh(this.h,"synthetic-keyup",this.Fl,void 0,this)},y5=function(a,b){return _ds.pg(a,10,b)},
z5=function(a){return(0,_ds.O)('<div class="devsite-popout" id="'+_ds.T(a.id)+'"><div class="devsite-popout-result devsite-suggest-results-container" devsite-hide></div></div>')},A5=function(a){var b='<button type="submit" class="button button-white devsite-search-project-scope">';a=_ds.R(a)+": \u0432\u0441\u0435 \u0440\u0435\u0437\u0443\u043b\u044c\u0442\u0430\u0442\u044b";return(0,_ds.O)(b+a+"</button>")},B5=function(a,b,c){var d='<button type="submit" class="button button-white devsite-suggest-all-results">';
b?(a=_ds.R(c)+": \u0432\u0441\u0435 \u0440\u0435\u0437\u0443\u043b\u044c\u0442\u0430\u0442\u044b",d+=a):(a='\u0412\u0441\u0435 \u0440\u0435\u0437\u0443\u043b\u044c\u0442\u0430\u0442\u044b \u043f\u043e\u0438\u0441\u043a\u0430 \u043f\u043e \u0437\u0430\u043f\u0440\u043e\u0441\u0443 "'+_ds.R(a)+'"',d+=a);return(0,_ds.O)(d+"</button>")},C5=function(a,b,c,d,e,f,h,k){a=(c?"":'<devsite-analytics-scope action="'+_ds.T(_ds.Tj("Restricted "+d))+'">')+'<a class="devsite-result-item-link" href="'+_ds.T(_ds.Tj(a))+
'"><span class="devsite-suggestion-fragment">'+_ds.R(b)+"</span>"+(k?'<span class="devsite-suggestion-fragment">'+_ds.R(k)+"</span>":"")+(e?'<span class="devsite-suggestion-fragment">'+_ds.R(e)+"</span>":"")+(_ds.sj(f)&&!h?'<span class="devsite-suggestion-fragment">'+_ds.R(f)+"</span>":"");c||(a+='<span class="devsite-result-item-confidential">\u041a\u043e\u043d\u0444\u0438\u0434\u0435\u043d\u0446\u0438\u0430\u043b\u044c\u043d\u043e</span>');return(0,_ds.O)(a+("</a>"+(c?"":"</devsite-analytics-scope>")))},
D5=function(a){var b=a.projectName,c=a.Dm,d=a.query,e=a.Qm;a=a.hg;b='<div class="devsite-suggest-wrapper '+(e?"":"devsite-search-disabled")+'"><div class="devsite-suggest-section"><div class="devsite-result-label">\u041f\u043e \u0432\u0430\u0448\u0435\u043c\u0443 \u0437\u0430\u043f\u0440\u043e\u0441\u0443 \u043d\u0438\u0447\u0435\u0433\u043e \u043d\u0435 \u043d\u0430\u0439\u0434\u0435\u043d\u043e.</div></div>'+((e?'<div class="devsite-suggest-footer">'+(c?A5(b):"")+B5(d,c,a)+"</div>":"")+"</div>");
return(0,_ds.O)(b)},E5=function(a){var b=a.ns,c=a.Fs,d=a.Ns,e=a.projectName,f=a.Dm,h=a.query,k=a.Ts,l=a.Qm;a=a.hg;var m='<div class="devsite-suggest-wrapper '+(l?"":"devsite-search-disabled")+'" tabindex="0" role="list"><div class="devsite-suggest-section">';if(0<d.length){m=m+'<div class="devsite-suggest-sub-section" role="listitem"><div class="devsite-suggest-header" id="devsite-suggest-header-partial-query" role="heading" aria-level="2">\u041f\u043e\u0438\u0441\u043a\u043e\u0432\u044b\u0435 \u043f\u043e\u0434\u0441\u043a\u0430\u0437\u043a\u0438'+
((f?'<span class="devsite-suggest-project">'+_ds.R(e)+"</span>":"")+'</div><devsite-analytics-scope category="Site-Wide Custom Events" label="Search" role="list" aria-labelledby="devsite-suggest-header-partial-query" action="Query Suggestion Click">');for(var n=d.length,r=0;r<n;r++){var t=d[r];m+='<div class="devsite-result-item devsite-nav-label" id="suggestion-partial-query-'+_ds.T(r)+'" role="listitem" index=":'+_ds.T(r)+'">'+C5(t.getPath(),t.getTitle(),_ds.ng(t,14),"Query Suggestion Click")+"</div>"}m+=
"</devsite-analytics-scope></div>"}m+=0<d.length&&0<b.length?'<hr role="none">':"";if(0<b.length){m=m+'<div class="devsite-suggest-sub-section" role="listitem"><div class="devsite-suggest-header" id="devsite-suggest-header-product" role="heading" aria-level="2">\u0421\u0442\u0440\u0430\u043d\u0438\u0446\u044b'+((f?'<span class="devsite-suggest-project">'+_ds.R(e)+"</span>":"")+'</div><devsite-analytics-scope category="Site-Wide Custom Events" label="Search" role="list" aria-labelledby="devsite-suggest-header-product" action="Page Suggestion Click">');
n=b.length;for(r=0;r<n;r++)t=b[r],m+='<div class="devsite-result-item devsite-nav-label" id="suggestion-product-'+_ds.T(r)+'" role="listitem" index=":'+_ds.T(r)+'">'+C5(t.getPath(),t.getTitle(),_ds.ng(t,14),"Page Suggestion Click",void 0,_ds.M(t,4),f)+"</div>";m+="</devsite-analytics-scope></div>"}m+=0<k.length&&0<b.length+d.length?'<hr role="none">':"";if(0<k.length){m=m+'<div class="devsite-suggest-sub-section" role="listitem"><div class="devsite-suggest-header" id="devsite-suggest-header-reference" role="heading" aria-level="2">\u0421\u0442\u0440\u0430\u043d\u0438\u0446\u044b \u0441\u043e \u0441\u0441\u044b\u043b\u043a\u0430\u043c\u0438'+
((f?'<span class="devsite-suggest-project">'+_ds.R(e)+"</span>":"")+'</div><devsite-analytics-scope category="Site-Wide Custom Events" label="Search" role="list" aria-labelledby="devsite-suggest-header-reference" action="Reference Suggestion Click">');n=k.length;for(r=0;r<n;r++)t=k[r],m+='<div class="devsite-result-item devsite-nav-label" id="suggestion-reference-'+_ds.T(r)+'" role="listitem" index=":'+_ds.T(r)+'">'+C5(t.getPath(),t.getTitle(),_ds.ng(t,14),"Reference Suggestion Click",_ds.M(t,3),
_ds.M(t,4),f,_ds.I(t,10)[0])+"</div>";m+="</devsite-analytics-scope></div>"}m+=0<c.length&&0<b.length+d.length+k.length?'<hr role="none">':"";if(0<c.length){m+='<div class="devsite-suggest-sub-section" role="listitem"><div class="devsite-suggest-header" id="devsite-suggest-header-other-products" role="heading" aria-level="2"><span role="columnheader">Products</span></div><devsite-analytics-scope category="Site-Wide Custom Events" label="Search" role="list" aria-labelledby="devsite-suggest-header-other-products" action="Product Suggestion Click">';
b=c.length;for(d=0;d<b;d++)k=c[d],m+='<div class="devsite-result-item devsite-nav-label" id="suggestion-other-products-'+_ds.T(d)+'" role="listitem" index=":'+_ds.T(d)+'">'+C5(k.getPath(),k.getTitle(),_ds.ng(k,14),"Product Suggestion Click")+"</div>";m+="</devsite-analytics-scope></div>"}m+="</div>"+(l?'<div class="devsite-suggest-footer">'+(f?A5(e):"")+B5(h,f,a)+"</div>":"")+"</div>";return(0,_ds.O)(m)},F5=function(){var a=_ds.ci.call(this)||this;a.R=!1;a.J={};a.K="";a.F=null;a.m=new _ds.Il;a.h=
null;a.M=!1;return a},L5=function(a){a.h&&(a.m.listen(a.h,"suggest-service-search",function(b){a:{var c=a.D.querySelector(".highlight");if(c&&(c=c.querySelector(".devsite-result-item-link"))){c.click();break a}G5(a,b.detail.originalEvent,!!a.F)}}),a.m.listen(a.h,"suggest-service-suggestions-received",function(b){return void H5(a,b)}),a.m.listen(a.h,"suggest-service-focus",function(){I5(a,"cloud-track-search-focus",null);a.M=!0;J5(a,!0)}),a.m.listen(a.h,"suggest-service-blur",function(){J5(a,!1)}),
a.m.listen(a.h,"suggest-service-input",function(){!a.J["Text Entered Into Search Bar"]&&a.h.query.trim()&&(a.dispatchEvent(new CustomEvent("devsite-analytics-observation",{detail:{category:"Site-Wide Custom Events",label:"Search",action:"Text Entered Into Search Bar"},bubbles:!0})),a.J["Text Entered Into Search Bar"]=!0);a.M&&(I5(a,"cloud-track-search-input",null),a.M=!1)}),a.m.listen(a.h,"suggest-service-navigate",function(b){return void K5(a,b)}),a.m.listen(document.body,"devsite-page-changed",
function(){return a.J={}}),a.h.Vm("SLASH",191));a.o&&a.m.listen(a.o,"submit",function(b){G5(a,b)});a.D&&a.m.listen(a.D,"click",function(b){var c=b.target,d=c.closest(".devsite-result-item-link");d&&(J5(a,!1),d="suggestion: "+d.getAttribute("href"),I5(a,"cloud-track-search-submit",d));c.classList.contains("devsite-search-project-scope")&&G5(a,b,!0)});a.Y&&a.m.listen(a.Y,"click",function(){return void J5(a,!0)});a.T&&a.m.listen(a.T,"click",function(){return void J5(a,!1)})},G5=function(a,b,c){c=void 0===
c?!1:c;var d,e;_ds.Va(function(f){if(1==f.j){b.preventDefault();b.stopPropagation();if(!a.hasAttribute("enable-search"))return f.G(0);a.J["Full Site Search"]||(a.dispatchEvent(new CustomEvent("devsite-analytics-observation",{detail:{category:"Site-Wide Custom Events",label:"Search",action:"Full Site Search"},bubbles:!0})),a.J["Full Site Search"]=!0);I5(a,"cloud-track-search-submit",a.L?"contains: "+a.L:"no match");d=c&&a.F?_ds.um(a.F):_ds.um(a.o.getAttribute("action"));e=new _ds.Hi(d.href);_ds.Ui(e,
"q",a.h.query);d.search=e.h.toString();return _ds.A(f,DevsiteApp.fetchPage(d.href),3)}J5(a,!1);_ds.B(f)})},K5=function(a,b){var c=b.detail;b=a.C.querySelector(".highlight");var d,e=Array.from(a.C.querySelectorAll(".devsite-result-item")),f=[],h=-1;if(b){var k=_ds.jl(b,function(m){return m.classList.contains("devsite-suggest-section")});f=Array.from(k.querySelectorAll(".devsite-result-item"));k=_ds.Rk(b.parentNode.parentNode);var l=_ds.Sk(b.parentNode.parentNode);h=e.indexOf(b)}switch(c.keyCode){case 37:if(!k&&
!l)return;b&&(c=b.getAttribute("index"),l?(d=l.querySelector('[index="'+c+'"]'))||(d=_ds.Eb(Array.from(l.querySelectorAll("[index]")))):k&&((d=k.querySelector('[index="'+c+'"]'))||(d=_ds.Eb(Array.from(k.querySelectorAll("[index]"))))));break;case 39:if(!k&&!l)return;b&&(c=b.getAttribute("index"),k?(d=k.querySelector('[index="'+c+'"]'))||(d=_ds.Eb(Array.from(k.querySelectorAll("[index]")))):l&&((d=l.querySelector('[index="'+c+'"]'))||(d=_ds.Eb(Array.from(l.querySelectorAll("[index]"))))));break;case 38:b?
(d=e[h-1])||(d=_ds.Eb(f)):d=_ds.Eb(e);break;case 40:b?(d=e[h+1])||(d=f[0]):d=e[0]}b&&(b.classList.remove("highlight"),b.removeAttribute("aria-selected"));d&&(a.H.setAttribute("aria-activedescendant",d.id),d.setAttribute("aria-selected","true"),d.classList.add("highlight"),d.scrollIntoViewIfNeeded&&d.scrollIntoViewIfNeeded()||d.scrollIntoView())},I5=function(a,b,c){a.dispatchEvent(new CustomEvent(b,{detail:{type:"search",name:b,position:"nav",metadata:{eventDetail:c}},bubbles:!0}))},J5=function(a,
b){if(a.R!==b){_ds.IE(a.h,b);if(a.R=b)a.setAttribute("search-active","");else{var c=a.D.querySelector(".highlight");c&&c.classList.remove("highlight");a.removeAttribute("search-active");a.setAttribute("aria-expanded","false");_ds.Jk(a.C)}a.hasAttribute("capture")||a.dispatchEvent(new CustomEvent("devsite-search-toggle",{detail:{active:b},bubbles:!0}))}},H5=function(a,b){a.L=null;b=b.detail;var c=b.suggestions,d=b.query;if(a.h.query.toLowerCase().startsWith(d.toLowerCase()))if(c){var e=c.Lb();0<e.length&&
(b=e.filter(function(t){return t.getTitle().includes(d)}),0<b.length&&(a.L=b[0].getTitle()));b=e.filter(function(t){return 2===t.rd()});c=e.filter(function(t){return 3===t.rd()});var f=e.filter(function(t){return 4===t.rd()}).slice(0,5),h=e.filter(function(t){return 1===t.rd()});e=b.length+f.length+h.length;for(var k=_ds.p(f),l=k.next();!l.done;l=k.next())l=l.value,l.setPath(_ds.um((a.F||"/s/results")+"/?q="+l.getTitle()).toString());var m=d.split(M5);c.forEach(function(t){return y5(t,_ds.I(t,10).filter(function(u){return m.some(function(v){return u.includes(v)})}))});
k=a.getAttribute("project-name")||"";l=a.hasAttribute("project-scope");var n=a.hasAttribute("enable-search"),r=a.getAttribute("tenant-name")||"";b={ns:b,projectName:k,Dm:l,Fs:h,Ns:f,query:d,Ts:c,Qm:n,hg:r};0===e?_ds.wl(a.C,D5,b):(_ds.wl(a.C,E5,b),N5(a,d));a.setAttribute("aria-expanded","true");a.C.removeAttribute("hidden")}else a.C.setAttribute("hidden",""),a.setAttribute("aria-expanded","false")},N5=function(a,b){b=new RegExp("("+_ds.Kd(b)+")","ig");a=_ds.p(a.C.querySelectorAll(".devsite-suggestion-fragment"));
for(var c=a.next();!c.done;c=a.next()){c=c.value;var d=c.innerHTML;d=d.replace(b,"<b>$1</b>");d=_ds.AG(d);_ds.Bd(c,d)}},l5={8:"backspace",9:"tab",13:"enter",16:"shift",17:"ctrl",18:"alt",19:"pause",20:"caps-lock",27:"esc",32:"space",33:"pg-up",34:"pg-down",35:"end",36:"home",37:"left",38:"up",39:"right",40:"down",45:"insert",46:"delete",48:"0",49:"1",50:"2",51:"3",52:"4",53:"5",54:"6",55:"7",56:"8",57:"9",59:"semicolon",61:"equals",65:"a",66:"b",67:"c",68:"d",69:"e",70:"f",71:"g",72:"h",73:"i",74:"j",
75:"k",76:"l",77:"m",78:"n",79:"o",80:"p",81:"q",82:"r",83:"s",84:"t",85:"u",86:"v",87:"w",88:"x",89:"y",90:"z",93:"context",96:"num-0",97:"num-1",98:"num-2",99:"num-3",100:"num-4",101:"num-5",102:"num-6",103:"num-7",104:"num-8",105:"num-9",106:"num-multiply",107:"num-plus",109:"num-minus",110:"num-period",111:"num-division",112:"f1",113:"f2",114:"f3",115:"f4",116:"f5",117:"f6",118:"f7",119:"f8",120:"f9",121:"f10",122:"f11",123:"f12",186:"semicolon",187:"equals",189:"dash",188:",",190:".",191:"/",
192:"`",219:"open-square-bracket",220:"\\",221:"close-square-bracket",222:"single-quote",224:"win"};_ds.g=f5.prototype;_ds.g.keyCode=function(a){this.m=a;return this};_ds.g.key=function(a){this.o=a;return this};_ds.g.shiftKey=function(a){this.O=a;return this};_ds.g.altKey=function(a){this.h=a;return this};_ds.g.ctrlKey=function(a){this.j=a;return this};_ds.g.metaKey=function(a){this.C=a;return this};_ds.g.target=function(a){this.J=a;return this};_ds.tb(h5,_ds.ch);
var v5=[27,112,113,114,115,116,117,118,119,120,121,122,123,19],w5="color date datetime datetime-local email month number password search tel text time url week".split(" "),k5;_ds.tb(x5,_ds.Vm);_ds.g=x5.prototype;_ds.g.n2=function(){return this.H};_ds.g.dka=function(a){this.J=a};_ds.g.o2=function(){return this.J};_ds.g.aka=function(a){this.F=a};_ds.g.g2=function(){return this.F};_ds.g.noa=function(a){this.L=a};_ds.g.K6=function(){return this.L};_ds.g.cka=function(a){this.M=a};_ds.g.Lm=_ds.ca(0);
_ds.g.dsa=function(a){j5(this.j,o5(0,arguments))};_ds.g.hga=function(a){return u5(this,this.j,o5(0,arguments))};_ds.g.Jma=function(a){this.K=$4(a)};_ds.g.n5=function(){return _ds.Vb(this.K)};
_ds.g.va=function(){x5.Ea.va.call(this);this.j={};_ds.Ah(this.h,"keydown",this.xl,!1,this);_ds.Ah(this.h,"synthetic-keydown",this.El,!1,this);_ds.QK&&(_ds.Ah(this.h,"keypress",this.Gl,!1,this),_ds.Ah(this.h,"synthetic-keypress",this.Hl,!1,this));_ds.Ah(this.h,"keyup",this.yl,!1,this);_ds.Ah(this.h,"synthetic-keyup",this.Fl,!1,this);this.h=null};_ds.g.nN=function(a){return"shortcut_"+a};_ds.g.yl=function(a){a=g5(a);_ds.Tn&&p5(this,a);_ds.QK&&!this.o&&q5(a)&&t5(this,a,!0)};
_ds.g.Fl=function(a){a=a.j();_ds.Tn&&p5(this,a);_ds.QK&&!this.o&&q5(a)&&t5(this,a,!0)};_ds.g.Gl=function(a){a=g5(a);32<a.h&&q5(a)&&(this.o=!0)};_ds.g.Hl=function(a){a=a.j();32<a.h&&q5(a)&&(this.o=!0)};_ds.g.xl=function(a){t5(this,g5(a))};_ds.g.El=function(a){t5(this,a.j())};
_ds.JE.prototype.Vm=Z4(1,function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];var e=this;this.h&&this.h.dispose();a&&(this.h=new x5(document),this.h.H=!1,this.h.Lm.apply(this.h,[a].concat(_ds.sa(c))),this.eventHandler.listen(this.h,"shortcut",function(f){var h=document;h.activeElement&&h.activeElement===h.body&&(f.preventDefault(),_ds.IE(e,!0))}))});x5.prototype.Lm=Z4(0,function(a,b){r5(this.j,o5(1,arguments),a)});var M5=/[ .()<>{}\[\]\/:,]+/,O5=0;_ds.q(F5,_ds.ci);F5.prototype.disconnectedCallback=function(){_ds.Ol(this.m);this.h&&(this.h.dispose(),this.h=null)};F5.prototype.attributeChangedCallback=function(a,b,c){switch(a){case "project-scope":this.K=c||"";this.h&&(this.h.K=this.K);break;case "url-scoped":this.F=c;break;case "disabled":this.H&&(this.H.disabled=null!==c)}};
F5.prototype.connectedCallback=function(){if(this.o=this.querySelector("form")){this.H=this.o.querySelector(".devsite-search-query");this.Y=this.o.querySelector(".devsite-search-button[search-open]");this.T=this.querySelector(".devsite-search-button[search-close]");var a="devsite-search-popout-container-id-"+ ++O5;this.H.setAttribute("aria-controls",a);this.D=_ds.xl(z5,{id:a});this.C=this.D.querySelector(".devsite-suggest-results-container");this.o.appendChild(this.D);this.hasAttribute("project-scope")&&
(this.K=this.getAttribute("project-scope"));this.hasAttribute("url-scoped")&&(this.F=this.getAttribute("url-scoped"));this.o&&this.H&&(this.h=new _ds.JE(this,this.o,this.H),this.h.m=!0,this.h.Ph=this.hasAttribute("enable-query-completion"),this.h.Cf=!0,this.h.Oh=!0,this.h.Qh=!0,this.h.K=this.K,this.h.m=this.hasAttribute("enable-suggestions"));L5(this)}};F5.prototype.ea=function(a){var b=this;_ds.jl(a.target,function(c){return c===b})||J5(this,!1)};
_ds.ja.Object.defineProperties(F5,{observedAttributes:{configurable:!0,enumerable:!0,get:function(){return["project-scope","url-scoped","disabled"]}}});F5.prototype.connectedCallback=F5.prototype.connectedCallback;F5.prototype.attributeChangedCallback=F5.prototype.attributeChangedCallback;F5.prototype.disconnectedCallback=F5.prototype.disconnectedCallback;try{window.customElements.define("devsite-search",F5)}catch(a){console.warn("devsite.app.customElement.DevsiteSearch",a)};})(_ds_www);
