(function(_ds){var window=this;'use strict';var cS=function(){_ds.av.apply(this,arguments);this.o=null},dS=function(a){return _ds.N(a,function c(){var d=this,e;return _ds.F(c,function(f){if(1==f.j)return _ds.A(f,_ds.cv(d),2);if(3!=f.j)return d.o?f.return(d.o):_ds.A(f,d.Ra(),3);e=f.h;d.o=new _ds.Ns(e);return f.return(d.o)})})},eS=function(a){var b=a.sb;a=_ds.O;var c=b[0].imageUrl,d=b[0].url,e=b[0].servePath,f=b[0].nextPlaylistUrl,h=b[0].redeemAnotherBtn,k=b[0].hideButtons,l=b[0].shareTitle,m=b[0].shareDescription;b=(0,_ds.O)('<div class="devsite-badger-award"><div class="devsite-badger-award-inner"><devsite-badge-awarded badge-name="'+
_ds.T(b[0].title)+'" badge-icon-url="'+_ds.T(_ds.Tj(c))+'" badge-url="'+_ds.T(_ds.Tj(d))+'"'+(e?' badge-path="'+_ds.T(e)+'"':"")+(l?' badge-share-title="'+_ds.T(l)+'"':"")+(m?' badge-share-description="'+_ds.T(m)+'"':"")+(f?' next-playlist-url="'+_ds.T(_ds.Tj(f))+'"':"")+(h?" redeem-another":"")+(k?" hide-buttons":"")+" dismiss></devsite-badge-awarded></div></div>");return a(b)},gS=function(){var a=_ds.BG.call(this,["devsite-badge-awarded"])||this;a.eventHandler=new _ds.Il(a);a.h=new _ds.Tl;a.Ha=
null;a.sb=[];a.m=new _ds.Ln(function(){return void fS(a)},250);return a},hS=function(a){null===a||void 0===a?void 0:a.setAttribute("show","")},iS=function(a){return _ds.N(a,function c(){var d=this;return _ds.F(c,function(e){if(1==e.j){if(!d.Ha)return e.return();d.h.remove("temp_badge");d.Ha.removeAttribute("show");return _ds.A(e,_ds.Jm(200),2)}if(3!=e.j)return _ds.Nk(d.Ha),d.Ha=null,_ds.A(e,_ds.Jm(250),3);d.m.ya();_ds.B(e)})})},fS=function(a){return _ds.N(a,function c(){var d=this,e,f,h,k;return _ds.F(c,
function(l){switch(l.j){case 1:e=d;if(d.Ha||0===d.sb.length||"error"===document.body.getAttribute("type")||jS.exec(document.location.pathname))return l.return();_ds.C(l,2);return _ds.A(l,window.customElements.whenDefined("devsite-badge-awarded"),4);case 4:_ds.D(l,3);break;case 2:_ds.E(l);case 3:f=d.sb.splice(0,1);h=_ds.xl(eS,{sb:f});if(!h)return l.return();d.eventHandler.listen(h,"click",function(m){(m=m.target)&&m.matches("button.dismiss")&&iS(e)});d.Ha=h;(k=h.querySelector("devsite-badge-awarded"))?
(_ds.Ml(d.eventHandler,k,"running",function(){hS(e.Ha)}),document.body.appendChild(d.Ha)):(document.body.appendChild(d.Ha),hS(d.Ha));_ds.B(l)}})})},kS=function(a){a.eventHandler.listen(document.body,"devsite-before-page-change",function(){return void iS(a)});a.eventHandler.listen(document.body,"devsite-award-granted",function(b){(b=b.oa)&&b.detail&&(a.sb.push(b.detail.award),a.m.ya())});a.eventHandler.listen(document.body,["devsite-page-loaded","devsite-page-changed"],function(){a.Ad();a:if(_ds.Sl(a.h)){var b=
a.h.get("temp_badge");if(b){var c=null;try{c=JSON.parse(b)}catch(e){a.h.remove("temp_badge");break a}if(c)if(3>c.displayCount){a.h.set("temp_badge",JSON.stringify(c));b=new URL(c.awardedBy,document.location.origin);var d=_ds.nm();if(!c.awardedBy||b.origin===d.origin&&b.pathname===d.pathname)a.sb.push(c),a.m.ya()}else a.h.remove("temp_badge")}}})};_ds.q(cS,_ds.av);_ds.g=cS.prototype;
_ds.g.uc=function(){return _ds.N(this,function b(){var c=this,d;return _ds.F(b,function(e){if(1==e.j)return _ds.A(e,dS(c),2);d=e.h;return e.return(d.uc())})})};
_ds.g.vd=function(a){a=void 0===a?!1:a;return _ds.N(this,function c(){var d=this,e,f,h,k,l;return _ds.F(c,function(m){switch(m.j){case 1:return _ds.A(m,dS(d),2);case 2:return e=m.h,f=_ds.jv(d,"getWalletId",a),h=_ds.kv(d,f),h||(h=e.vd(a),_ds.mv(d,f,h)),k=null,_ds.C(m,3,4),_ds.A(m,h,6);case 6:k=m.h;case 4:_ds.Ea(m);_ds.lv(d,f);_ds.Ha(m,5);break;case 3:throw l=_ds.E(m),l;case 5:return m.return(k)}})})};
_ds.g.me=function(){return _ds.N(this,function b(){var c=this,d;return _ds.F(b,function(e){if(1==e.j)return _ds.A(e,dS(c),2);d=e.h;return e.return(d.me())})})};_ds.g.Ad=function(){return _ds.N(this,function b(){var c=this,d,e,f,h;return _ds.F(b,function(k){switch(k.j){case 1:return _ds.A(k,dS(c),2);case 2:return d=k.h,e=_ds.jv(c,"syncWallet"),f=_ds.kv(c,e),f||(f=d.Ad(),_ds.mv(c,e,f)),_ds.C(k,3,4),_ds.A(k,f,4);case 4:_ds.Ea(k);_ds.lv(c,e);_ds.Ha(k,0);break;case 3:throw h=_ds.E(k),h;}})})};
_ds.g.Wd=function(){return _ds.N(this,function b(){var c=this,d;return _ds.F(b,function(e){if(1==e.j)return _ds.A(e,dS(c),2);d=e.h;d.Wd();_ds.B(e)})})};var jS=/\/redeem.*|\/u[\/]?.*|\/settings[\/]?.*?/;_ds.q(gS,_ds.BG);gS.prototype.connectedCallback=function(){kS(this)};gS.prototype.disconnectedCallback=function(){_ds.Ol(this.eventHandler);iS(this)};
gS.prototype.Ad=function(){return _ds.N(this,function b(){var c,d,e,f,h;return _ds.F(b,function(k){switch(k.j){case 1:return _ds.A(k,DevsiteApp.whenReady(),2);case 2:return _ds.A(k,window.customElements.whenDefined("devsite-user"),3);case 3:c=document.querySelector("devsite-user#devsite-user");if(!c)return k.return();d=!1;_ds.C(k,4);return _ds.A(k,c.isSignedIn(),6);case 6:d=k.h;_ds.D(k,5);break;case 4:_ds.E(k);case 5:if(!d)return k.return();e=new cS;return _ds.A(k,e.uc(),7);case 7:f=k.h;if(!f)return k.return();
h=new _ds.vv;_ds.C(k,8);return _ds.A(k,h.Z(),10);case 10:_ds.D(k,0);break;case 8:_ds.E(k),_ds.B(k)}})})};try{window.customElements.define("devsite-badger",gS)}catch(a){console.warn("Unrecognized DevSite custom element - DevsiteBadger",a)};})(_ds_www);
