(function(_ds){var window=this;/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
'use strict';var MY=function(a,b){JY()&&(b=KY()?"translate3d("+b+"px,0px,0px)":"translate("+b+"px,0px)",_ds.Rn(a,LY(),b))},PY=function(){var a=_ds.ci.call(this)||this;a.M=-1;a.o=new _ds.Il;a.J=new _ds.Il;a.F=0;a.K=new MutationObserver(function(){return NY(a)});a.R=new _ds.Ln(function(){NY(a);OY(a)},15);a.C=0;a.h=0;a.D=0;a.m=0;a.H=!1;return a},RY=function(a){a.o.listen(a,"devsite-search-toggle",function(b){b=b.oa;_ds.ll(b.target,"devsite-top-logo-row-middle")&&(b.detail.active?a.setAttribute("search-active",
""):a.removeAttribute("search-active"))});a.o.listen(document.body,"devsite-sitemask-hidden",function(){return document.body.removeAttribute("devsite-book-nav--open")});a.o.listen(window,"resize",function(){return QY(a)});a.o.listen(document.body,["devsite-page-loaded","devsite-content-updated"],function(){QY(a)});a.o.listen(a,"click",function(b){b.defaultPrevented||"devsite-hamburger-menu"!=b.target.getAttribute("id")||(b.preventDefault(),b.stopPropagation(),document.body.setAttribute("devsite-book-nav--open",
""),a.dispatchEvent(new CustomEvent("devsite-sitemask-show",{bubbles:!0})))})},QY=function(a){window.requestAnimationFrame(function(){return a.R.ya()})},SY=function(a,b){return(a=a.querySelector(b))?a.getBoundingClientRect().height:0},NY=function(a){a.C=SY(a,".devsite-top-logo-row-wrapper-wrapper");a.h=SY(a,".devsite-collapsible-section");a.D=SY(a,".devsite-doc-set-nav-row");a.setAttribute("top-row--height",a.C);a.setAttribute("bottom-row--height",a.h);a.setAttribute("bottom-tabs--height",a.D);document.body.style.setProperty("--devsite-js-header-top-row-height",
a.C+"px");document.body.style.setProperty("--devsite-js-header-lower-section-height",a.h+"px");document.body.style.setProperty("--devsite-js-header-lower-tabs-height",a.D+"px");document.body.style.setProperty("--devsite-js-header-height",a.Vh()+"px");TY(a)},UY=function(a){if(!a.querySelector(".devsite-search-background")&&(a=a.querySelector(".devsite-top-logo-row-middle"))){var b=document.createElement("div");b.classList.add("devsite-search-background");b.style.opacity=1;a.appendChild(b)}},TY=function(a){var b=
a.querySelector(".devsite-collapsible-section");a.m>=a.h&&!a.hasAttribute("bottom-row--hidden")?a.setAttribute("bottom-row--hidden",""):a.m<a.h-a.D&&a.hasAttribute("bottom-row--hidden")&&a.removeAttribute("bottom-row--hidden");b&&a.m!==a.M&&(document.body.style.setProperty("--devsite-js-header-lower-tabs-offset",a.m+"px"),_ds.Rn(b,"transform","translate3d(0, -"+a.m+"px, 0)"),OY(a),a.M=a.m)},VY=function(a){var b=a.querySelector(".devsite-top-logo-row-middle"),c=a.querySelector("devsite-search"),d=
a.querySelector(".devsite-search-background");if(b&&c&&d){_ds.Ol(a.J);a.F&&window.cancelAnimationFrame(a.F);c.removeAttribute("transition");a.removeAttribute("search-expanded");var e=new _ds.jk(b.offsetWidth,b.offsetHeight);b=new _ds.jk(c.offsetWidth,c.offsetHeight);var f=_ds.io(c,"margin"),h="rtl"===document.documentElement.getAttribute("dir")?1:-1,k=(e.width-f.left-f.right)/b.width;e=(e.width-(b.width+f.left+f.right))*h;var l=(f=a.hasAttribute("search-active"))?e:0,m=f?k:1;_ds.Rn(d,{opacity:1,width:b.width+
"px",height:b.height+"px"});MY(c,a.hasAttribute("search-active")?0:e);_ds.Ml(a.J,d,_ds.em,function(){var n=a.querySelector("devsite-search"),r=a.querySelector(".devsite-search-background");r&&(r.style.opacity=0);n&&(n.removeAttribute("transition"),MY(n,0),a.hasAttribute("search-active")?a.setAttribute("search-expanded",""):a.removeAttribute("search-expanded"))});a.F=window.requestAnimationFrame(function(){c.setAttribute("transition","");if(JY()){var n=KY()?"scale3d("+m+",1,1)":"scale("+m+",1)";_ds.Rn(d,
LY(),n)}MY(c,l)})}},WY=function(a,b){var c,d,e,f;_ds.Va(function(h){if(1==h.j){if(!a.hasAttribute("billboard"))return h.return();c=a.querySelector("devsite-search");d=a.querySelector("devsite-search input.devsite-search-query");e=a.querySelector(".devsite-header-billboard-search devsite-search");f=e.querySelector("input.devsite-search-query");if(!b)return e.removeAttribute("disabled"),document.activeElement===d&&f.focus(),c.setAttribute("disabled",""),h.G(0);c.removeAttribute("disabled");return document.activeElement!==
f?h.G(3):_ds.A(h,_ds.Fm(),4)}3!=h.j&&d.focus();e.setAttribute("disabled","");_ds.B(h)})},OY=function(a){0===a.h?a.setAttribute("no-lower-row",""):a.removeAttribute("no-lower-row");a.querySelector(".devsite-header-billboard")?a.setAttribute("billboard",""):a.removeAttribute("billboard")},XY=function(a,b){for(var c=0;c<b.attributes.length;++c){var d=b.attributes.item(c);a.hasAttribute(d.name)||b.removeAttribute(d.name)}for(c=0;c<a.attributes.length;++c)d=a.attributes.item(c),b.setAttribute(d.name,d.value)},
YY=function(a,b,c){b=b.querySelector(c);c=a.querySelector(c);b&&c&&(a.H=!0,_ds.ei(a,c,b))};var JY=_ds.Db(function(){return!_ds.zk||0<=_ds.Fc(_ds.tN,9)}),KY=_ds.Db(function(){return _ds.Bk||_ds.DE||_ds.Tn&&0<=_ds.Fc(_ds.tN,10)||_ds.zk&&0<=_ds.Fc(_ds.tN,10)}),LY=_ds.Db(function(){return _ds.zk&&9==_ds.Zn?"-ms-transform":"transform"});_ds.q(PY,_ds.ci);_ds.g=PY.prototype;_ds.g.attributeChangedCallback=function(a,b,c){switch(a){case "offset":this.m=parseFloat(this.getAttribute("offset"))||0;TY(this);break;case "search-active":VY(this);break;case "bottom-row--hidden":a=null!==c,b=this.querySelector("devsite-search input.devsite-search-query"),c=this.querySelector(".devsite-header-billboard-search devsite-search input.devsite-search-query"),b&&c&&(a?b.value=c.value:c.value=b.value),WY(this,a)}};
_ds.g.connectedCallback=function(){RY(this);UY(this);OY(this);NY(this);this.K.observe(this,{childList:!0,subtree:!0});TY(this);var a=_ds.nm();this.L=_ds.Vi(_ds.Xi(a.href),"authuser")};_ds.g.disconnectedCallback=function(){_ds.Ol(this.o);this.K.disconnect()};_ds.g.Vh=function(){return this.C+this.h-this.m};_ds.g.Bq=function(){return this.C+this.h};
_ds.g.Xa=function(a){this.H=!1;if(a){YY(this,a,".devsite-header-upper-tabs");YY(this,a,".devsite-collapsible-section");YY(this,a,".devsite-product-name-wrapper");YY(this,a,"devsite-language-selector");YY(this,a,"devsite-shell-activate-button");var b=a.querySelector("devsite-search"),c=this.querySelector("devsite-search");b&&c&&XY(b,c);c=a.querySelector("devsite-user");b=this.querySelector("devsite-user");c&&b&&(XY(c,b),c=_ds.nm(),c=_ds.Vi(_ds.Xi(c.href),"authuser"),c!==this.L&&(this.L=c,b.refresh()));
_ds.ei(this,this.querySelector("cloudx-additional-tabs"),a.querySelector("cloudx-additional-tabs"),this.querySelector(".devsite-top-logo-row-middle"));_ds.ei(this,this.querySelector(".devsite-header-link"),a.querySelector(".devsite-header-link"),this.querySelector("devsite-language-selector"))}!this.H&&a&&(_ds.Jk(this),this.appendChild(a));UY(this);QY(this)};_ds.ja.Object.defineProperties(PY,{observedAttributes:{configurable:!0,enumerable:!0,get:function(){return["offset","search-active","bottom-row--hidden"]}}});
PY.prototype.updateContent=PY.prototype.Xa;PY.prototype.disconnectedCallback=PY.prototype.disconnectedCallback;PY.prototype.connectedCallback=PY.prototype.connectedCallback;PY.prototype.attributeChangedCallback=PY.prototype.attributeChangedCallback;try{window.customElements.define("devsite-header",PY)}catch(a){console.warn("devsite.app.customElement.DevsiteHeader",a)};})(_ds_www);
